context:
  name: cargo-llvm-cov
package:
  version: 1.8.1
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
about:
  repository: https://github.com/jqlang/${{ name }}
  description: |
    [exposed]

    ${{ name }} = "${{ name }}"
