context:
  name: cargo-llvm-cov
package:
  version: "0.8.4"
  name: ${{ name }}
build:
  number: 1
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
tests:
  - script: ${{ name }} llvm-cov --help
about:
  homepage: https://github.com/taiki-e/cargo-llvm-cov
  license: MIT OR Apache-2.0
  summary: Cargo subcommands for LLVM coverage tools
  description: >
    A collection of Cargo subcommands for working with LLVM coverage tools such as llvm-cov.
  repository: https://github.com/taiki-e/cargo-llvm-cov
