context:
  name: cargo-llvm-cov
package:
  version: "0.8.5"
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    content: |
      $ROOT = git rev-parse --show-toplevel
      . $ROOT/scripts/util.ps1
      cargo install $name @(Get-Cargo-Arg)
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
tests:
  - script: ${{ name }} llvm-cov --help
about:
  homepage: https://github.com/taiki-e/cargo-llvm-cov
  license: MIT OR Apache-2.0
  summary: Cargo subcommands for LLVM coverage tools
  description: >
    A collection of Cargo subcommands for working with LLVM coverage tools such as llvm-cov.
  repository: https://github.com/taiki-e/cargo-llvm-cov
