context:
  name: cargo-llvm-cov
package:
  version: "0.8.0"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - ${{ compiler("rust") }}
tests:
  - script: ${{ name }} llvm-cov --help
about:
  homepage: https://github.com/taiki-e/cargo-llvm-cov
  license: MIT OR Apache-2.0
  summary: Cargo subcommands for LLVM coverage tools
  description: >
    A collection of Cargo subcommands for working with LLVM coverage tools such as llvm-cov.
  repository: https://github.com/taiki-e/cargo-llvm-cov
