context:
  name: mkcert
package:
  version: 1.4.4
  name: ${{ name }}
build:
  number: 6
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - "%PREFIX%/bin/${{ name }}.exe --help"
about:
  repository: https://github.com/FiloSottile/mkcert
  description: |
    [exposed]

    ${{ name }} = "${{ name }}"
