context:
  name: ttyd
package:
  version: "1.7.7"
  name: ${{ name }}
build:
  number: 2
  script: pwsh -Command "& $RECIPE_DIR/build-${{ name }}.ps1"

tests:
  - script: pwsh -Command "exit test-path ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/${{ name }}*"
