context:
  name: ttyd
package:
  version: "1.7.7"
  name: ${{ name }}
build:
  number: 7
  script: pwsh -Command "& $RECIPE_DIR/build-${{ name }}.ps1"
requirements:
  build:
    - binutils
    - brotlipy
    - c-compiler
    - cmake 3.*
    - curl
    - cxx-compiler
    - fonttools
    - json-c
    - libwebsockets
    - nodejs
    - zlib

tests:
  - script: pwsh -Command "resolve-path $PREFIX/bin/${{ name }}${{'.exe' if win}}"
about:
  homepage: https://github.com/tsl0922/ttyd
  license: MIT OR Apache-2.0
  summary: A simple command-line tool for sharing terminal over the web
  description: >
    ttyd is a simple command-line tool for sharing terminal over the web. It is
    based on libwebsockets and provides a web-based terminal emulator.
  repository: https://github.com/tsl0922/ttyd
