context:
  name: ttyd
package:
  version: "1.7.7"
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - "%PREFIX%/bin/${{ name }}.exe --help"
