context:
  name: ttyd
package:
  version: "1.7.7"
  name: ${{ name }}
build:
  number: 2
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
    - if: win
      then:
        - "%PREFIX%/bin/${{ name }}.exe --help"
    - if: linux
      then:
        - "$PREFIX/bin/${{ name }} --help"
