context:
  name: ttyd
package:
  version: "1.7.7"
  name: ${{ name }}
build:
  number: 7
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - brotlipy
    - c-compiler
    - cmake 3.*
    - curl
    - cxx-compiler
    - fonttools
    - json-c
    - libwebsockets
    - make
    - nodejs
    - zlib
    - pkg-config
    - if: unix
      then:
        - autoconf
        - automake
        - file
    - if: macos
      then:
        - openssl
  run:
    - libwebsockets
    - json-c

tests:
  - script: pwsh -Command "resolve-path $PREFIX/bin/${{ name }}${{'.exe' if win}}"
  - requirements:
      run:
        - curl
    script:
      - $PREFIX/bin/${{ name }}${{'.exe' if win}} --port 7681 pwsh
      - curl -sI http://localhost:7681

about:
  homepage: https://github.com/tsl0922/ttyd
  license: MIT OR Apache-2.0
  summary: A simple command-line tool for sharing terminal over the web
  description: >
    ttyd is a simple command-line tool for sharing terminal over the web. It is
    based on libwebsockets and provides a web-based terminal emulator.
  repository: https://github.com/tsl0922/ttyd
