context:
  name: ttyd
  version: "1.7.7"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/tsl0922/ttyd/archive/refs/tags/${{ version }}.tar.gz
build:
  number: 8
  script: pwsh -Command "& $RECIPE_DIR/build-${{ name }}.ps1"
requirements:
  build:
    - if: unix
      then:
        - brotlipy
        - cmake 3.*
        - fonttools
        - make
        - nodejs
        - pkg-config
        - c-compiler
        - cxx-compiler
        - autoconf
        - automake
        - file
  host:
    - if: unix
      then:
        - json-c
        - libwebsockets
        - zlib
    - if: macos
      then:
        - openssl
  run:
    - if: unix
      then:
        - json-c
        - libwebsockets
        - zlib
    - if: macos
      then:
        - openssl

tests:
  - if: unix
    then:
      - package_contents:
          bin:
            - ${{ name }}
      - requirements:
          run:
            - curl
        script:
          - pwsh -Command "Start-Process $PREFIX/bin/${{ name }}${{'.exe' if win}} -ArgumentList '--port 7681 pwsh'"
          - curl -sI http://localhost:7681
          - pwsh -Command "Stop-Process -Name ttyd -Force"

about:
  homepage: https://github.com/tsl0922/ttyd
  license: MIT OR Apache-2.0
  summary: A simple command-line tool for sharing terminal over the web
  description: >
    ttyd is a simple command-line tool for sharing terminal over the web. It is
    based on libwebsockets and provides a web-based terminal emulator.
  repository: https://github.com/tsl0922/ttyd
