context:
  name: ttyd
package:
  version: "1.7.7"
  name: ${{ name }}
build:
  number: 8
  script: pwsh -Command "& $RECIPE_DIR/build-${{ name }}.ps1"

tests:
  - package_contents:
      bin:
        - ${{ name }}
about:
  homepage: https://github.com/tsl0922/ttyd
  license: MIT OR Apache-2.0
  summary: A simple command-line tool for sharing terminal over the web
  description: >
    ttyd is a simple command-line tool for sharing terminal over the web. It is
    based on libwebsockets and provides a web-based terminal emulator.
  repository: https://github.com/tsl0922/ttyd
