context:
  name: sys-rhino
package:
  version: "8.29.26063.11001"
  name: ${{ name }}
build:
  number: 9
  script:
    interpreter: powershell
    content: |
      new-item $env:PREFIX/Scripts -itemType Directory -Force -ErrorAction SilentlyContinue
      (Get-Content $env:RECIPE_DIR/sys-install-rhino.ps1) -replace '\$template_version', "`$version=`"$env:PKG_VERSION`"" | Set-Content $env:PREFIX/Scripts/sys-install-rhino.ps1
      Write-Output (Get-Content $env:PREFIX/Scripts/sys-install-rhino.ps1)
requirements:
  run:
    - aria2
tests:
  - script:
      interpreter: powershell
      content: |
        install-${{name}}.ps1
        Resolve-Path "C:\Program Files\Rhino 8\System\Rhino.exe"
