context:
  name: sys-icaros
package:
  version: "3.3.5.0"
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    content: |
      new-item $env:PREFIX/Scripts -itemType Directory -Force -ErrorAction SilentlyContinue
      Copy-Item $env:RECIPE_DIR/install-${{name}}.ps1 $env:PREFIX/Scripts/
requirements:
  run:
    - sys-install

extra:
  update: |
    $latest_version=get-version-winget "x/Xanashi/Icaros"
    $latest_version="$latest_version".replace("000","0")
    update-recipe $latest_version
    
