context:
  name: sys-dnc
package:
  version: "18.2.2"
  name: ${{ name }}
build:
  number: 6
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  run:
    - aria2
tests:
  - script:
      interpreter: powershell
      content: |
        sys-install-dnc.ps1
        ls "C:/Program Files/Adobe/Adobe DNG Converter/"
        Resolve-Path "C:/Program Files/Adobe/Adobe DNG Converter/Adobe DNG Converter.exe"
        (Get-Item "C:/Program Files/Adobe/Adobe DNG Converter/Adobe DNG Converter.exe").VersionInfo.ProductVersion
