context:
  name: cargo-unused-features
package:
  version: 0.2.0
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-${{ name }}.ps1
about:
  description: |
    [exposed]

    ${{ name }} = "${{ name }}"
