context:
  name: cargo-unused-features
package:
  version: 0.2.0
  name: ${{ name }}
build:
  number: 7
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: linux
      then:
        - pkg-config
        - openssl
  host:
    - ${{ 'openssl' if linux }}

tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
about:
  homepage: https://github.com/taiki-e/cargo-unused-features
  license: MIT
  summary: Detect unused Cargo features in Rust projects
  description: >
    cargo-unused-features is a Cargo subcommand that analyzes
    Rust projects to detect which Cargo features are unused.
    This helps developers clean up feature flags and reduce
    unnecessary compilation overhead.
  documentation: https://github.com/taiki-e/cargo-unused-features#usage
  repository: https://github.com/taiki-e/cargo-unused-features
