context:
  name: cargo-unused-features
package:
  version: 0.2.0
  name: ${{ name }}
build:
  number: 5
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - ${{ compiler('rust') }}
    - if: linux
      then:
        - pkg-config
        - openssl
  run:
    - if: linux
      then:
        - openssl

tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
about:
  homepage: https://github.com/taiki-e/cargo-unused-features
  license: MIT
  summary: Detect unused Cargo features in Rust projects
  description: >
    cargo-unused-features is a Cargo subcommand that analyzes
    Rust projects to detect which Cargo features are unused.
    This helps developers clean up feature flags and reduce
    unnecessary compilation overhead.
  documentation: https://github.com/taiki-e/cargo-unused-features#usage
  repository: https://github.com/taiki-e/cargo-unused-features
