context:
  name: robin-map
  version: "1.4.1"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  - url: https://github.com/Tessil/robin-map/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 0
requirements:
  build:
    - ${{ compiler('c') }}
    - cmake 3.*
    - ninja
tests:
  - package_contents:
      include:
        - tsl/robin_map.h
about:
  repository: https://github.com/Tessil/robin-map

extra:
  update: get-version-github "Tessil/robin-map"
  changelog: get-changelog-github "Tessil/robin-map"
