context:
  name: sys-rhino-inside-revit
  version: "1.35.9607.16352"
package:
  version: ${{ version }}
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    content: |
      new-item $env:PREFIX/Scripts -itemType Directory -Force -ErrorAction SilentlyContinue
      (Get-Content $env:RECIPE_DIR/install-${{name}}.ps1) -replace '\$template_version', "`$version=`"$env:PKG_VERSION`"" | Set-Content $env:PREFIX/Scripts/install-${{name}}.ps1
      Write-Output (Get-Content $env:PREFIX/Scripts/install-${{name}}.ps1)
requirements:
  run:
    - aria2
    - sys-install
