context:
  name: sys-rhino-inside-revit
package:
  version: "1.35.9540.6370"
  name: ${{ name }}
build:
  number: 10
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  run:
    - aria2
