context:
  name: bitcomet
package:
  version: "2.20.1.19"
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1

tests:
  - package_contents:
      bin:
        - ${{ name }}/BitComet
about:
  homepage: https://www.bitcomet.com
  summary: A powerful BitTorrent/HTTP/FTP download client
  description: >
    BitComet is a powerful, clean, fast, and easy-to-use BitTorrent/HTTP/FTP
    download client. It supports simultaneous downloads, download queue,
    selected downloads in torrent package, fast-resume, disk cache, proxy
    servers, IP filtering, port mapping, and more.
