context:
  name: bitcomet
package:
  version: "2.17.9.28"
  name: ${{ name }}
build:
  number: 0
  script:
    - pwsh -f ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1
tests:
  - script:
      - pwsh -Command "Test-Path $env:PREFIX/bin/${{ name }}/BitComet${{'.exe' if win}}"
