context:
  name: bitcomet
package:
  version: "2.18.11.3"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script:
      - pwsh -Command "Test-Path $env:PREFIX/bin/${{ name }}/BitComet${{'.exe' if win}}"
