context:
  name: open-interpreter
  version: "0.0.40"

package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/openinterpreter/openinterpreter/archive/refs/tags/rust-v${{ version }}.tar.gz
build:
  number: 7
  script:
    interpreter: bash
    content:
      - if: win
        then:
          - rm $BUILD_PREFIX/Library/usr/bin/link.exe
          - ./scripts/build-interpreter-release.sh --install-dir $PREFIX/bin --home $PREFIX
      - if: osx
        then: ./scripts/build-interpreter-release.sh --install-dir $PREFIX/bin --home $PREFIX
      - if: linux and x86_64
        then: ./scripts/build-interpreter-release.sh --install-dir $PREFIX/bin --home $PREFIX
      - if: linux and aarch64
        then: ./scripts/build-interpreter-release.sh --install-dir $PREFIX/bin --home $PREFIX

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ "git"  if win }}
    - ${{ "pkg-config" if linux }}
    - python
    - ${{ "patchelf"  if linux }}
  host:
    - ${{ "openssl 3.*" if linux }}
    - ${{ "libcap" if linux }}
tests:
  - package_contents:
      bin:
        - interpreter

about:
  repository: https://github.com/openinterpreter/openinterpreter
extra:
  update: |
    $latest_version = get-version-github -repo "openinterpreter/openinterpreter"
    "$latest_version".Replace("rust-v", "")
  changelog: get-changelog-github openinterpreter/openinterpreter
