context:
  name: open-interpreter
  version: "0.0.40"

package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/openinterpreter/openinterpreter/archive/refs/tags/rust-v${{ version }}.tar.gz
build:
  number: 7
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - python
    - ${{ "pkg-config" if linux }}
    - ${{ "patchelf"  if linux }}
    - ${{ "llvm-tools"  if win }}
  host:
    - ${{ "openssl 3.*" if linux }}
    - ${{ "libcap" if linux }}
tests:
  - package_contents:
      bin:
        - interpreter

about:
  repository: https://github.com/openinterpreter/openinterpreter
extra:
  update: |
    $latest_version = get-version-github -repo "openinterpreter/openinterpreter"
    "$latest_version".Replace("rust-v", "")
  changelog: get-changelog-github openinterpreter/openinterpreter
