context:
  name: zed
  version: "0.217.3"
package:
  version: ${{ version }}
  name: ${{ name }}
build:
  number: 2
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
source:
  git: https://github.com/zed-industries/zed.git
  tag: v${{ version }}
tests:
  - script: pwsh -Command "Resolve-Path ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/${{ name }}${{'.exe' if win}}"
