context:
  name: zed
  version: "0.217.3"
package:
  version: ${{ version }}
  name: ${{ name }}
build:
  number: 2
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
source:
  url: https://github.com/zed-industries/zed/archive/refs/tags/v${{ version }}.tar.gz
tests:
  - package_contents:
      bin:
        - ${{ name }}
