context:
  name: zed
  version: "0.225.9"
package:
  version: "0.225.9"
  name: ${{ name }}
source:
  url: https://github.com/zed-industries/zed/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  build:
    - rust
tests:
  - package_contents:
      bin:
        - ${{ name }}
