package:
  name: rawpy
  version: 0.24.0

build:
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-rawpy.ps1 -version ${{ version }}
  number: 0
  string: vfx2024_${{ hash }}_${{ build_number }}

requirements:
  host:
    - python 3.11.*
    - pip
  run:
    - python 3.11.*
    - numpy 1.24.*
about:
  repository: https://github.com/letmaik/rawpy
