context:
  name: toolbox
package:
  version: 0.0.33
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/toolbox/archive/refs/tags/v${{ version }}.tar.gz
build:
  noarch: python
  number: 0
  script: pip install ./python -v

requirements:
  host:
    - python 3.13.*
    - pip
    - setuptools
    - wheel
  run:
    - python >= 3.13
    - lazy-loader
    - rich

tests:
  - python:
      imports:
        - toolbox
