# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml
c_compiler:
  - gcc # [linux]
  - clang # [osx]
  - vs2022 # [win]
c_compiler_version: # [unix]
  - 14 # [linux]
  - 19 # [osx]

cxx_compiler:
  - gxx # [linux]
  - clangxx # [osx]
  - vs2022 # [win]
cxx_compiler_version: # [unix]
  - 14 # [linux]
  - 19 # [osx]

c_stdlib:
  - sysroot # [linux]
  - macosx_deployment_target # [osx]
  - vs # [win]
c_stdlib_version: # [unix]
  - 2.28 # [linux]
  - 11.0 # [osx and arm64]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 11.0                       # [osx and arm64]

rust_compiler:
  - rust # [os.environ.get("CI", "") == "true"]

cuda_compiler:
  - cuda-nvcc
cuda_compiler_version:
  - None
  - 12.9                       # [((linux and not ppc64le) or win64) and os.environ.get("CF_CUDA_ENABLED", "False") == "True"]
cuda_compiler_version_min:
  - None                       # [osx or ppc64le]
  - 12.9                       # [(linux and not ppc64le) or win64]
