context:
  name: clang-format
package:
  version: "22.1.6"
  name: ${{ name }}
build:
  number: 1
  script:
    - if: win
      then: mkdir "%PREFIX%\bin" && copy "%BUILD_PREFIX%\Library\bin\clang-format.exe" "%PREFIX%\bin\clang-format.exe"
      else: mkdir $PREFIX/bin && cp "$BUILD_PREFIX/bin/clang-format" "$PREFIX/bin/clang-format"
requirements:
  build:
    - clang-format
  host:
    - libclang
tests:
  - package_contents:
      bin:
        - clang-format
extra:
  update: |
    [Version](get-version-conda-forge clang-format)
  changelog: get-changelog-github llvm/llvm-project
