context:
  name: spek
package:
  version: "0.8.5"
  name: ${{ name }}
build:
  number: 0
  script:
    - pwsh -f ${{'$env:RECIPE_DIR'}}\build-${{ name }}.ps1
tests:
  - script:
      - pwsh -Command "Test-Path $env:PREFIX/bin/${{ name }}/${{ name }}${{'.exe' if win}}"
about:
  homepage: https://spek.cc
  license: GPL-3.0-or-later
  summary: Acoustic spectrum analyser for audio files
  description: >
    Spek is an acoustic spectrum analyser written in C++.
    It uses FFmpeg for audio decoding and wxWidgets for the GUI.
    It works across *BSD, Linux, Windows, and macOS, allowing users
    to view the spectrogram of audio files and analyze spectral content.
  documentation: https://spek.cc
  repository: https://github.com/alexkay/spek
