context:
  name: libcap-ng
  version: "0.9.1"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  - url: https://github.com/stevegrubb/libcap-ng/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 10
  script:
    - ./autogen.sh
    - ./configure --prefix=$PREFIX
    - make -j$(nproc)
    - make install
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - autoconf
    - automake
    - libtool
    - diffutils
    - pkg-config

tests:
  - package_contents:
      lib:
        - libcap-ng
about:
  repository: https://github.com/stevegrubb/libcap-ng
