context:
  name: passmark-performance-test
package:
  name: ${{ name }}
  version: "11.1"
build:
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
  number: 0
tests:
  - script: pwsh -Command "& ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/${{ name }}${{'.exe' if win}} --help"
about:
  homepage: https://www.passmark.com/products/performancetest/
  summary: Benchmarking software for Windows PCs
  description: >
    PassMark PerformanceTest is a benchmarking tool for Windows
    PCs that allows users to evaluate the performance of their
    computer. It provides a range of tests including CPU, 2D/3D
    graphics, disk, and memory benchmarks, and allows comparison
    against other systems.
  documentation: https://www.passmark.com/products/performancetest/
  repository: https://www.passmark.com/
