context:
  name: dism-plus-plus
package:
  version: 10.1.1002.2
  name: ${{ name }}
build:
  number: 7
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - package_contents:
      bin:
        - Dism++x64
about:
  homepage: https://www.chuyu.me/en/index.html
  summary: Advanced Windows system management and optimization tool
  description: >
    Dism++ is a Windows system utility that extends the capabilities
    of the built-in DISM tool. It allows users to clean, optimize,
    and manage Windows images, remove bloatware, manage drivers,
    and maintain system health.
  documentation: https://www.chuyu.me/en/index.html
  repository: https://www.chuyu.me/
