context:
  name: dism-plus-plus
package:
  version: 10.1.1002.2
  name: ${{ name }}
build:
  number: 6
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
about:
  repository: https://github.com/Chuyu-Team/Dism-Multi-language
