context:
  name: esp-generate
package:
  version: "1.0.1"
  name: ${{ name }}
build:
  number: 0
  script:
    - pwsh -f ${{'$env:RECIPE_DIR'}}\build-${{ name }}.ps1
tests:
  - script:
      - pwsh -Command "& ${{'$env:PREFIX'}}/bin/${{ name }}${{'.exe' if win}} --help"
