context:
  name: cargo-bloat
package:
  version: "0.12.1"
  name: ${{ name }}
build:
  number: 11
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
tests:
  - package_contents:
      bin:
        - ${{ name }}
about:
  repository: https://github.com/RazrFalcon/cargo-bloat

extra:
  update: get-version-crateio -name $name
