context:
  name: cargo-bloat
package:
  version: 0.12.1
  name: ${{ name }}
build:
  number: 7
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - ${{ 'rust' if linux}}
tests:
  - package_contents:
      bin:
        - ${{ name }}
about:
  homepage: https://github.com/rylev/cargo-bloat
  license: MIT
  summary: Analyze Rust binaries to see what takes most space
  description: >
    cargo-bloat is a Cargo subcommand to analyze Rust binaries,
    showing which functions and dependencies occupy the most
    space. It helps developers optimize binary size and performance.
  documentation: https://github.com/rylev/cargo-bloat#usage
  repository: https://github.com/rylev/cargo-bloat

