context:
  name: nssm
package:
  name: ${{ name }}
  version: "2.24"
build:
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
  number: 0
tests:
  - script:
      - "%PREFIX%/bin/${{ name }}.exe help"
