context:
  name: nssm
  version: "2.24"
package:
  name: ${{ name }}
  version: ${{ version }}
source:
  url: https://nssm.cc/release/nssm-${{ version }}.zip
build:
  number: 0
  script:
    interpreter: powershell
    contents: |
      New-Item $env:PREFIX/bin -ItemType Directory
      Copy-Item "./Win64/${env:PKG_NAME}.exe" "$env:PREFIX/bin/${env:PKG_NAME}.exe"
tests:
  - package_contents:
      bin:
        - ${{ name }}
