context:
  name: nssm
  version: "2.24"
package:
  name: ${{ name }}
  version: ${{ version }}
source:
  url: https://nssm.cc/release/nssm-${{ version }}.zip
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1
tests:
  - package_contents:
      bin:
        - ${{ name }}
