context:
  name: nssm
package:
  name: ${{ name }}
  version: "2.24"
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script:
            - pwsh -Command "Resolve-Path $env:PREFIX/bin/${{name}}${{'.exe' if win}}"
