context:
  name: sys-fonts-hack
  number: 0
  version: "3.4.0"
recipe:
  version: ${{ version }}
  name: ${{ name }}
outputs:
  - staging:
      name: ${{ name }}-build
    build:
      script:
        interpreter: bash
        file: build-${{ name }}.sh
    requirements:
      build:
        - fonttools
        - brotlipy
      ignore_run_exports:
        from_package:
          - fonttools
          - brotlipy

  - package:
      name: ${{ name }}-ttf
    inherit: ${{ name }}-build
    requirements:
      run:
        - sys-fonts
    build:
      noarch: generic
      number: ${{ number }}
      files:
        - fonts/*.ttf
    test:
      package_contents:
        files:
          - fonts/*.ttf
  - package:
      name: ${{ name }}-woff2
    inherit: ${{ name }}-build
    build:
      noarch: generic
      number: ${{ number }}
      files:
        - fonts/*.woff2
    test:
      package_contents:
        files:
          - fonts/*.woff2
about:
  repository: https://github.com/ryanoasis/nerd-fonts
