context:
  name: libkrunfw
  version: "5.2.1"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  - url: https://github.com/containers/libkrunfw/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 1
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  run_exports:
    - ${{ pin_subpackage('libkrunfw', upper_bound='x.x.x') }}
tests:
  - package_contents:
      lib:
        - libkrunfw
about:
  repository: https://github.com/containers/libkrunfw
