context:
  name: libkrunfw
  version: "5.3.0"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  - url: https://github.com/containers/libkrunfw/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 0
  script:
    interpreter: powershell
    content: |
      sudo apt-get update
      sudo apt-get install -y make gcc bc bison flex elfutils python3-pyelftools curl patch libelf-dev
      make -j$(nproc)
      make install PREFIX=$PREFIX
requirements:
  host:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - libcap-ng-dev
tests:
  - package_contents:
      lib:
        - libkrunfw
about:
  repository: https://github.com/containers/libkrunfw
