context:
  name: calibre
package:
  version: 8.8.0
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - if not exist "%PREFIX%/bin/${{ name }}/${{ name }}-portable.exe" exit /b 1 ))
about:
  repository: https://github.com/kovidgoyal/calibre
