context:
  name: calibre
package:
  version: "9.4.0"
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1
tests:
  - package_contents:
      bin:
        - ${{ name }}/${{ name }}-portable

about:
  homepage: https://calibre-ebook.com
  license: GPL-3.0-or-later
  summary: Comprehensive e-book management software
  description: >
    Calibre is a powerful and easy-to-use e-book manager.
    It supports organizing, converting, editing, and
    transferring e-books to various devices. It also
    includes a built-in e-book reader and server for
    accessing your library remotely.
  documentation: https://manual.calibre-ebook.com
  repository: https://github.com/kovidgoyal/calibre
