package:
  version: 8.0.1
  name: calibre
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-calibre.ps1
tests:
- script:
  - if not exist "%PREFIX%/bin/calibre/calibre-portable.exe" exit /b 1 ))
