context:
  name: vinaya-cli
  version: "2026.4.16"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/toolbox/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 0
  script:
    interpreter: powershell
    content: |
      $ROOT = git rev-parse --show-toplevel
      . $ROOT/scripts/util.ps1
      Set-Location ./tools/vinaya
      cargo install --path . @(Get-Cargo-Arg)

requirements:
  build:
    - ${{ compiler('rust') }}
tests:
  - script: vinaya --help
