context:
  name: vinaya-cli
  version: "2026.8.4"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/toolbox/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 6
requirements:
  build:
    - ${{ compiler('rust') }}
tests:
  - script: vinaya --help

extra:
  update: get-version-github -repo "Glatzel/toolbox"
  changelog: get-changelog-github -repo "Glatzel/toolbox"
