context:
  name: vs-build-tools
package:
  version: "18.1.1"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script:
      - pwsh -Command "Resolve-Path $env:PREFIX/bin/vs_BuildTools${{'.exe' if win}}"
