context:
  name: atuin
package:
  version: "18.13.6"
  name: ${{ name }}
build:
  number: 0
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
  run:
    - ${{'ble-sh' if linux}}
tests:
  - package_contents:
      bin:
        - ${{ name }}
about:
  repository: https://github.com/atuinsh/atuin
