context:
  name: ttyw
  version: "2026.5.1"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/toolbox/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 0
requirements:
  build:
    - ${{ compiler('rust') }}
tests:
  - script: ttyw --help
