context:
  name: cargo-fuzz
package:
  version: "0.9.138"
  name: ${{ name }}
build:
  number: 0
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  run:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - clang
    - diffutils
tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
  - requirements:
      run:
        - rustup-init
    script:
      interpreter: ${{"powershell" if win else "bash"}}
      content:
        - rustup-init -y --default-toolchain nightly --profile minimal
        - if: unix
          then: . "$HOME/.cargo/env"
        - if: win
          then: copy-item $env:GITHUB_WORKSPACE/packages/cargo-fuzz/test-files/* ./ -recurse
          else: cp -r $GITHUB_WORKSPACE/packages/cargo-fuzz/test-files/* ./
        - cargo +nightly fuzz run --fuzz-dir ./ fuzz_target_1

about:
  repository: https://github.com/rust-fuzz/cargo-fuzz

extra:
  update: get-version-crateio -name cargo-fuzz
  changelog: get-changelog-github rust-fuzz/cargo-fuzz
