context:
  name: crsdk
  number: 1
recipe:
  name: ${{ name }}
  version: "2.2.0"
source:
  - if: win
    then:
      - url: https://support.d-imaging.sony.co.jp/disoft_DL/SDK_DL/win?fm=en-us
        file_name: crsdk.zip
  - if: osx
    then:
      - url: https://support.d-imaging.sony.co.jp/disoft_DL/SDK_DL/mac?fm=en-us
        file_name: crsdk.zip
  - if: linux and x86_64
    then:
      - url: https://support.d-imaging.sony.co.jp/disoft_DL/SDK_DL/linux_x86?fm=en-us
        file_name: crsdk.zip
  - if: linux and aarch64
    then:
      - url: https://support.d-imaging.sony.co.jp/disoft_DL/SDK_DL/linux_64?fm=en-us
        file_name: crsdk.zip
outputs:
  - staging:
      name: ${{ name }}-build
    build:
      script:
        interpreter: powershell
        file: build-${{ name }}.ps1
  - package:
      name: ${{ name }}-rt
    inherit: ${{ name }}-build
    requirements:
      run_exports:
        - ${{ pin_subpackage('crsdk-rt', upper_bound='x.x.x') }}
    build:
      number: ${{ number }}
      files:
        - if: osx
          then: lib/*.dylib
        - if: linux
          then: lib/*.so*
        - if: win
          then:
            - Library/*.lib
            - Library/bin/*.dll
    tests:
      - package_contents:
          lib:
            - Cr_Core
  - package:
      name: ${{ name }}-dev
    inherit: ${{ name }}-build
    requirements:
      run_exports:
        - ${{ pin_subpackage('crsdk-rt', upper_bound='x.x.x') }}
    build:
      number: ${{ number }}
    tests:
      - package_contents:
          include:
            - CameraRemote_SDK.h
about:
  homepage: https://support.d-imaging.sony.co.jp/app/sdk/licenseagreement_d/en-US.html
  summary: Software Development Kit for remote control of Sony cameras
  description: >
    The Camera Remote SDK enables developers to integrate Sony cameras into
    custom software applications for remote control and data retrieval. It
    provides a high-level command system for efficient development, allowing
    operations such as shutter release, live view monitoring, and image
    transfer.

extra:
  update: |
    $latest_version = get-version-url -url "https://support.d-imaging.sony.co.jp/app/sdk/licenseagreement_d/en-US.html" -pattern 'CrSDK_v(\d+\.\d+\.\d+)_'
    [Version]"$latest_version"
  changelog: echo "https://support.d-imaging.sony.co.jp/app/sdk/licenseagreement_d/en-US.html"
