context:
  name: furmark
package:
  version: "2.10.2.0"
  name: ${{ name }}
build:
  number: 1
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script:
      - pwsh -Command "Resolve-Path ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/${{ name }}/${{ name }}${{'.exe' if win}}"
about:
  homepage: https://geeks3d.com/furmark
  summary: GPU stress test and benchmarking tool
  description: >
    FurMark is a lightweight but intensive GPU stress-testing and
    benchmarking tool. It is designed to test the stability and
    thermal performance of graphics cards by rendering a highly
    demanding 3D scene, helping users identify potential issues
    with cooling or overclocking.
  documentation: https://geeks3d.com/furmark
  repository: https://geeks3d.com/furmark
