context:
  name: github-action-runner
package:
  version: "2.332.0"
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1
about:
  repository: https://github.com/actions/runner
