context:
  name: github-action-runner
package:
  version: "2.331.0"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
