context:
  name: yazi-full
package:
  version: "26.1.22"
  name: ${{ name }}
requirements:
  run:
    - fd-find
    - ffmpeg
    - fzf
    - imagemagick
    - jq
    - poppler
    - resvg
    - ripgrep
    - yazi
    - zoxide
    - 7zip
    - if: unix
      then:
        - chafa
        - file
        - xclip
        - xsel
tests:
  - script: yazi --debug
