context:
  name: yazi-full
package:
  version: "26.5.6"
  name: ${{ name }}
build:
  number: 0
requirements:
  run:
    - fd-find
    - ffmpeg
    - fzf
    - imagemagick
    - jq
    - poppler
    - resvg
    - ripgrep
    - yazi
    - zoxide
    - 7zip
    - if: unix
      then:
        - chafa
        - file
        - ueberzugpp
        - xclip
        - xsel
tests:
  - script: yazi --debug

extra:
  update: get-version-conda-forge yazi
