context:
  name: pkg-config-lite
package:
  version: 0.28.1
  name: ${{ name }}
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
- script:
  - '%PREFIX%/bin/${{ name }}/pkg-config.exe --help'
about:
  description: |
    [dependencies]
    ${{ name }} = "*"
    [exposed]
    pkg-config = "bin/${{ name }}/pkg-config"
