context:
  name: sony-camera-remote-sdk
package:
  name: ${{ name }}
  version: 2.0.0
build:
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%/build-${{ name }}.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-${{ name }}.ps1
  number: 1
about:
  homepage: https://support.d-imaging.sony.co.jp/app/sdk/licenseagreement_d/en-US.html
  license: Proprietary
  summary: Software Development Kit for remote control of Sony cameras
  description: >
    The Camera Remote SDK enables developers to integrate Sony cameras into custom software applications for remote control and data retrieval. It provides a high-level command system for efficient development, allowing operations such as shutter release, live view monitoring, and image transfer.
