context:
  name: ueberzugpp
  version: "2.9.8"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  - url: https://github.com/jstkdng/ueberzugpp/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 8
  script: pwsh -Command "& $RECIPE_DIR/build-${{ name }}.ps1"
requirements:
  build:
    - c-compiler
    - cxx-compiler
    - cmake 3.*
    - ninja
  host:
    - expat
    - libvips
    - libsixel
    - chafa
    - openssl
    - tbb-devel
    - nlohmann_json
    - cli11
    - spdlog
    - fmt
    - range-v3
  run:
    - expat
    - libvips
    - libsixel
    - chafa
    - openssl
    - tbb
    - nlohmann_json
    - cli11
    - spdlog
    - fmt
    - range-v3

tests:
  - package_contents:
      bin:
        - ueberzug
  - script: ueberzug layer -h
