context:
  name: fornax-py
  version: "0.0.15"
package:
  version: "0.0.15"
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/fornax/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - python 3.13.*
    - pip
    - libraw-dev
  host:
    - libraw-dev
  run:
    - python >= 3.13
    - lazy-loader
    - pydantic
    - msgspec

tests:
  - python:
      imports:
        - fornax
