context: 
  name: fornax-py
package:
  version: 0.0.10
  name: ${{ name }}
build:
  number: 1
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"

requirements:
  host:
    - python 3.13.*
    - pip
  run:
    - python >= 3.13
    - lazy-loader
    - pydantic
    - msgspec

tests:
  - python:
      imports:
        - fornax
