context:
  name: fornax-py
  version: "0.0.14"
package:
  version: "0.0.14"
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/fornax/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"

requirements:
  build:
    - ${{ 'rust' if linux}}
    - libraw
  host:
    - python 3.13.*
    - pip
    - libraw
  run:
    - python >= 3.13
    - lazy-loader
    - pydantic
    - msgspec
    - libraw

tests:
  - python:
      imports:
        - fornax
