context:
  name: fornax-py
  version: "0.0.17"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/fornax/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python 3.11.*
    - pip
    - libraw-dev
  run:
    - python >= 3.11
    - lazy-loader
    - pydantic
    - msgspec

tests:
  - python:
      imports:
        - fornax

extra:
  update: get-version-github -repo "Glatzel/fornax"
  changelog: get-changelog-github "Glatzel/fornax"
