context:
  name: fornax-py
  version: "0.0.12"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/fornax/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 1
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"

requirements:
  build:
    - ${{ compiler("rust") }}
  host:
    - python 3.13.*
    - pip
  run:
    - python >= 3.13
    - lazy-loader
    - pydantic
    - msgspec

tests:
  - python:
      imports:
        - fornax
