context:
  name: slumber
package:
  version: 3.1.1
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
    - if: win
      then:
        - pwsh -f $RECIPE_DIR/build-${{ name }}.ps1
tests:
  - script:
    - if: win
      then:
        - "%PREFIX%/bin/${{ name }}/${{ name }}.exe help"
    - if: linux
      then:
        - "$PREFIX/bin/${{ name }}/${{ name }} help"

about:
  repository: https://github.com/LucasPickering/slumber
  description: |
    [exposed]

    ${{ name }} = "bin/${{ name }}/${{ name }}"
