context:
  name: slumber
package:
  version: 3.1.0
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - "%PREFIX%/bin/${{ name }}/${{ name }}.exe help"
about:
  repository: https://github.com/LucasPickering/slumber
  description: |
    [exposed]

    ${{ name }} = "bin/${{ name }}/${{ name }}"
