context:
  name: termscp
package:
  version: "0.19.1"
  name: ${{ name }}
build:
  number: 3
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - rust
    - c-compiler
    - cxx-compiler
    - cmake 3.30.*
    - make
    - nasm
  host:
    - if: unix
      then:
        - openssl
  run:
    - if: unix
      then:
        - openssl


tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
about:
  homepage: https://termscp.veeso.dev
  license: MIT
  summary: Feature-rich terminal file transfer and explorer
  description: >
    Termscp is a terminal user interface (TUI) application that facilitates
    secure file transfers and remote file system exploration. It supports
    multiple protocols including SCP, SFTP, FTP, FTPS, S3, SMB, and WebDAV,
    allowing users to manage files across local and remote systems seamlessly.
    Built with Rust, it is cross-platform and runs on Linux, macOS, FreeBSD,
    NetBSD, and Windows.
  documentation: https://termscp.veeso.dev/docs
  repository: https://github.com/veeso/termscp
