context:
  name: termscp
package:
  version: "0.19.0"
  name: ${{ name }}
build:
  number: 0
  script:
    - pwsh -f ${{'$env:RECIPE_DIR'}}\build-${{ name }}.ps1
tests:
  - script:
      - pwsh -Command "& ${{'$env:PREFIX'}}/bin/${{ name }}${{'.exe' if win}} --help"

about:
  homepage: https://termscp.veeso.dev
  license: MIT
  summary: Feature-rich terminal file transfer and explorer
  description: >
    Termscp is a terminal user interface (TUI) application that facilitates
    secure file transfers and remote file system exploration. It supports
    multiple protocols including SCP, SFTP, FTP, FTPS, S3, SMB, and WebDAV,
    allowing users to manage files across local and remote systems seamlessly.
    Built with Rust, it is cross-platform and runs on Linux, macOS, FreeBSD,
    NetBSD, and Windows.
  documentation: https://termscp.veeso.dev/docs
  repository: https://github.com/veeso/termscp
