context:
  name: termscp
package:
  version: 0.18.0
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - "%PREFIX%/bin/${{ name }}.exe --help"

about:
  repository: https://github.com/termscp/${{ name }}
  description: |
    [exposed]

    ${{ name }} = "${{ name }}"
