context:
  version: 1.7.0
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %PREFIX%\build.ps1
package:
  name: jq
  version: ${{ version }}
source:
  git: https://github.com/jqlang/jq.git
tests:
- script:
  - jq --help
