context:
  name: cargo-codspeed
package:
  version: "4.4.1"
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    content: |
      $ROOT = git rev-parse --show-toplevel
      . $ROOT/scripts/util.ps1
      cargo install $name @(Get-Cargo-Arg)
requirements:
  build:
    - ${{ compiler('rust') }}
tests:
  - package_contents:
      bin:
        - ${{name}}
