[project]
authors = ["Glatzel <893016099@qq.com.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "rawpy"
platforms = ["win-64"]
version = "0.1.0"

[dependencies]
python = ">=3.11,<3.13"
libraw = "*"
lcms2 = "*"
libjpeg-turbo = "*"
zlib = "*"
jasper = "*"
[pypi-dependencies]
cython = "*"
setuptools = "*"

[feature.vfx2024.dependencies]
python = "3.11.*"
[feature.vfx2024.pypi-dependencies]
numpy = "==1.24.*"

[feature.vfx2025.dependencies]
python = "3.11.*"
[feature.vfx2025.pypi-dependencies]
numpy = "==1.26.*"

[environments]
vfx2024 = ["vfx2024"]
vfx2025 = ["vfx2025"]
