context:
  name: libraw
package:
  version: 0.21.4
  name: ${{ name }}
build:
  number: 0
  script:
    - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
about:
  repository: https://github.com/Libraw/Libraw
