context:
  name: libraw
  version: "0.22.0"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  - url: https://github.com/LibRaw/LibRaw/archive/refs/tags/${{ version }}.tar.gz
  - url: https://github.com/LibRaw/LibRaw-cmake/archive/refs/heads/master.zip
    target_directory: LibRaw-cmake
build:
  number: 3
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - c-compiler
    - cxx-compiler
    - cmake 3.*
    - pkg-config
    - make
    - if: win
      then:
        - vs2022_win-64
  host:
    - zlib
    - lcms2
    - openjpeg
    - Jasper
    - if: osx
      then:
        llvm-openmp
  run:
    - zlib
    - lcms2
    - openjpeg
    - Jasper
    - if: osx
      then:
        llvm-openmp

tests:
  - package_contents:
      include:
        - libraw/libraw.h
      lib:
        - raw
      bin:
        - 4channels
        - dcraw_emu
        - raw-identify
        - simple_dcraw
  - requirements:
      run:
        - curl
    script:
      - curl https://www.rawsamples.ch/raws/nikon/d1/RAW_NIKON_D1.NEF -o RAW_NIKON_D1.NEF
      - raw-identify -u RAW_NIKON_D1.NEF
      - simple_dcraw -v -T RAW_NIKON_D1.NEF
about:
  homepage: https://www.libraw.org
  license: BSD-2-Clause
  summary: Library for reading RAW files from digital cameras
  description: >
    LibRaw is an open-source C/C++ library for reading RAW
    files from digital cameras. It supports a wide range of
    camera models and RAW formats, providing easy access
    to image data for processing, conversion, or analysis.
  documentation: https://www.libraw.org/docs
  repository: https://github.com/LibRaw/LibRaw
