context:
  name: libraw
package:
  version: "0.21.5"
  name: ${{ name }}
build:
  number: 2
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake 3.*
    - pkg-config
    - lcms2
    - zlib
    - openjpeg
    - Jasper
    - make
    - if: linux and x86_64
      then:
        - openmp
    - if: win
      then:
        - openmp
        - vs2022_win-64
  run:
    - zlib
    - lcms2
    - openjpeg
    - Jasper
    - if: linux and x86_64
      then:
        - openmp
    - if: win
      then:
        - openmp

tests:
  - package_contents:
      include:
        - libraw/libraw.h
      lib:
        - raw
      bin:
        - 4channels
        - dcraw_emu
        - raw-identify
        - simple_dcraw
  - requirements:
      run:
        - curl
    script:
      - curl https://www.rawsamples.ch/raws/nikon/d1/RAW_NIKON_D1.NEF -o RAW_NIKON_D1.NEF
      - raw-identify -u RAW_NIKON_D1.NEF
      - simple_dcraw -v -T RAW_NIKON_D1.NEF
about:
  homepage: https://www.libraw.org
  license: BSD-2-Clause
  summary: Library for reading RAW files from digital cameras
  description: >
    LibRaw is an open-source C/C++ library for reading RAW
    files from digital cameras. It supports a wide range of
    camera models and RAW formats, providing easy access
    to image data for processing, conversion, or analysis.
  documentation: https://www.libraw.org/docs
  repository: https://github.com/LibRaw/LibRaw
