context:
  name: libraw
package:
  version: 0.21.4
  name: ${{ name }}
build:
  number: 3
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-${{ name }}.ps1
about:
  homepage: https://www.libraw.org
  license: BSD-2-Clause
  summary: Library for reading RAW files from digital cameras
  description: >
    LibRaw is an open-source C/C++ library for reading RAW
    files from digital cameras. It supports a wide range of
    camera models and RAW formats, providing easy access
    to image data for processing, conversion, or analysis.
  documentation: https://www.libraw.org/docs
  repository: https://github.com/LibRaw/LibRaw
