context:
  name: libraw
package:
  version: "0.21.5"
  name: ${{ name }}
build:
  number: 2
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake 3.*
    - pkg-config
    - lcms2
    - zlib
    - openjpeg
    - Jasper
    - make
    - if: linux
      then: 
        - openmp
    - if: win
      then: 
        - openmp

about:
  homepage: https://www.libraw.org
  license: BSD-2-Clause
  summary: Library for reading RAW files from digital cameras
  description: >
    LibRaw is an open-source C/C++ library for reading RAW
    files from digital cameras. It supports a wide range of
    camera models and RAW formats, providing easy access
    to image data for processing, conversion, or analysis.
  documentation: https://www.libraw.org/docs
  repository: https://github.com/LibRaw/LibRaw
