context:
  name: libraw
  version: "0.22.1"
  number: 0
recipe:
  version: ${{ version }}
  name: ${{ name }}
source:
  - url: https://github.com/LibRaw/LibRaw/archive/refs/tags/${{ version }}.tar.gz
  - url: https://github.com/LibRaw/LibRaw-cmake/archive/refs/heads/master.zip
    target_directory: LibRaw-cmake
outputs:
  - staging:
      name: ${{ name }}-build
    build:
      script:
        interpreter: ${{ "powershell" if win else "bash" }}
        file: build-${{ name }}.${{ "ps1" if win else "sh" }}
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake 3.*
        - pkg-config
        - ninja

      host:
        - zlib
        - lcms2
        - openjpeg
        - jasper
        - ${{ 'llvm-openmp' if osx }}

  - package:
      name: ${{ name }}-rt
    inherit: ${{ name }}-build
    requirements:
      run_exports:
        - ${{ pin_subpackage('libraw-rt', upper_bound='x.x') }}
    build:
      number: ${{ number }}
      files:
        - if: osx
          then: lib/*.dylib
        - if: linux
          then: lib/*.so*
        - if: win
          then:
            - Library/*.lib
            - Library/bin/*.dll
    tests:
      - package_contents:
          lib:
            - raw

  - package:
      name: ${{ name }}-dev
    inherit: ${{ name }}-build
    requirements:
      host:
        - ${{ name }}-rt
      run_exports:
        - ${{ pin_subpackage('libraw-rt', upper_bound='x.x') }}
    build:
      number: ${{ number }}
    tests:
      - package_contents:
          include:
            - libraw/libraw.h

  - package:
      name: ${{ name }}-app
    inherit: ${{ name }}-build
    requirements:
      host:
        - ${{ name }}-rt
    build:
      number: ${{ number }}
      files:
        - ${{ 'bin/*' if unix }}
        - ${{ 'Library/bin/*' if win }}
    tests:
      - package_contents:
          bin:
            - 4channels
            - dcraw_emu
            - raw-identify
            - simple_dcraw
      - requirements:
          run:
            - curl
        script:
          - curl https://www.rawsamples.ch/raws/nikon/d1/RAW_NIKON_D1.NEF -o RAW_NIKON_D1.NEF
          - raw-identify -u RAW_NIKON_D1.NEF
          - simple_dcraw -v -T RAW_NIKON_D1.NEF

about:
  homepage: https://www.libraw.org
  license: BSD-2-Clause
  summary: Library for reading RAW files from digital cameras
  description: >
    LibRaw is an open-source C/C++ library for reading RAW
    files from digital cameras. It supports a wide range of
    camera models and RAW formats, providing easy access
    to image data for processing, conversion, or analysis.
  documentation: https://www.libraw.org/docs
  repository: https://github.com/LibRaw/LibRaw
