context:
  name: shook
  version: "2026.4.3"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  # url: https://github.com/Glatzel/toolbox/archive/refs/tags/v${{ version }}.tar.gz
  git: https://github.com/Glatzel/toolbox.git
  branch: shook-msb
build:
  number: 5
requirements:
  build:
    - ${{ compiler('rust') }}
    - make
    - flex
    - bison
    - bc
    - pyelftools
    - libudev
    - sqlite
    - diffutils
    - pkg-config
  host:
    - libcap-ng-dev
tests:
  - script: shook --help
