context:
  name: shook
  version: "2026.5.1"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/toolbox/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 0
requirements:
  build:
    - ${{ compiler('rust') }}
    - diffutils
    - pkg-config
  host:
    - libcap-ng-dev
    - microsandbox-libkrunfw
  ignore_run_exports:
      from_package:
        - libcap-ng-dev
tests:
  - script: shook --help
