context:
  name: rhino-inside-revit-init
package:
  version: "1.35.9540.6370"
  name: ${{ name }}
build:
  number: 8
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  run:
    - aria2
tests:
  - script:
      interpreter: powershell
      content: |
        rhino-inside-revit-init
