context:
  name: cargo-espflash
package:
  version: "4.3.0"
  name: ${{ name }}
build:
  number: 7
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements: 
  build: 
    - if: linux
      then:
        - c-compiler
        - cxx-compiler
tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
about:
  homepage: https://esp-rs.github.io/espflash
  license: MIT
  summary: Flash and monitor ESP32/ESP8266 microcontrollers via Cargo
  description: >
    cargo-espflash is a Cargo subcommand that allows flashing and
    monitoring ESP32 and ESP8266 microcontrollers directly from
    the command line. It integrates with Rust embedded projects
    for easy development and debugging.
  documentation: https://esp-rs.github.io/espflash
  repository: https://github.com/esp-rs/espflash
