context:
  name: 7z
package:
  version: 1.37.0
  name: ${{ name }}
build:
  number: 7
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - package_contents:
      bin:
        - 7z
  - script: 7z --help
