context:
  name: librepcb
package:
  name: ${{ name }}
  version: "1.3.0"
build:
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
  number: 0
tests:
  - script:
      - if: win
        then:
          - pwsh -Command "Test-Path %PREFIX%/bin/${{ name }}/${{ name }}${{'.exe' if win}}"
