context:
  name: librepcb
package:
  name: ${{ name }}
  version: "1.3.0"
build:
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
  number: 0
tests:
  - package_contents:
      bin:
        - ${{ name }}/bin/${{ name }}
about:
  homepage: https://librepcb.org
  license: GPL-3.0-only
  summary: LibrePCB is a free EDA software to develop printed circuit boards
  description: >
    LibrePCB is a free EDA software to develop printed circuit boards. It features an
    easy-to-use interface, a powerful library concept, and is designed to be extensible.
  repository: https://github.com/LibrePCB/LibrePCB
