context:
  name: mason
package:
  name: ${{ name }}
  version: "0.0.3"
build:
  number: 1
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - package_contents:
      bin:
        - ${{ name }}/install.ps1
