context:
  name: mason
  version: "0.0.4"
package:
  name: ${{ name }}
  version: "0.0.4"
source:
  url: https://github.com/Glatzel/mason/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1
tests:
  - package_contents:
      bin:
        - ${{ name }}/install.ps1
        - ${{ name }}/*/Mason.dll
