context:
  name: mason
  version: "0.0.4"
package:
  name: ${{ name }}
  version: "0.0.4"
source:
  url: https://github.com/Glatzel/mason/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - package_contents:
      bin:
        - ${{ name }}/install.ps1
        - ${{ name }}/*/Mason.dll
  - script:
      - pwsh -Command "Resolve-Path C:/ProgramData/Autodesk/Revit/Addins/Revit2018/mason.addin"
      - pwsh -Command "Resolve-Path C:/ProgramData/Autodesk/Revit/Addins/Revit2019/mason.addin"
      - pwsh -Command "Resolve-Path C:/ProgramData/Autodesk/Revit/Addins/Revit2020/mason.addin"
      - pwsh -Command "Resolve-Path C:/ProgramData/Autodesk/Revit/Addins/Revit2021/mason.addin"
      - pwsh -Command "Resolve-Path C:/ProgramData/Autodesk/Revit/Addins/Revit2022/mason.addin"
      - pwsh -Command "Resolve-Path C:/ProgramData/Autodesk/Revit/Addins/Revit2023/mason.addin"
      - pwsh -Command "Resolve-Path C:/ProgramData/Autodesk/Revit/Addins/Revit2024/mason.addin"
      - pwsh -Command "Resolve-Path C:/ProgramData/Autodesk/Revit/Addins/Revit2025/mason.addin"
