context:
  name: dufs
package:
  version: 0.45.0
  name: ${{ name }}
build:
  number: 6
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
about:
  homepage: https://github.com/muesli/dufs
  license: MIT
  summary: Terminal-based disk usage/free space viewer
  description: >
    dufs is a terminal-based utility to visualize disk usage
    and free space. It provides a clear overview of file system
    usage with colored bars and supports multiple file systems
    in a single view.
  documentation: https://github.com/muesli/dufs#usage
  repository: https://github.com/muesli/dufs
