context:
  name: dufs
package:
  version: "0.46.0"
  name: ${{ name }}
build:
  number: 0
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
about:
  homepage: https://github.com/sigoden/dufs
  license: MIT
  summary: A file server that supports static serving, uploading, searching,
    accessing control, webdav...
  description: >
    Dufs is a distinctive utility file server that supports static serving,
    uploading, searching, accessing control, webdav...
  documentation: https://github.com/sigoden/dufs
  repository: https://github.com/sigoden/dufs

extra:
  update: get-version-crateio -name $name
  changelog: get-changelog-github "sigoden/dufs"
