context:
  name: opencolorio-config-aces
package:
  version: "4.0.0"
  name: ${{ name }}
build:
  number: 1
  noarch: generic
  script:
    interpreter: powershell
    file: build.ps1
tests:
  - script: pwsh -Command "Resolve-Path ${{'$env:PREFIX' if win else '$PREFIX'}}/ocio/*.ocio"
