context:
  name: cpu-z
package:
  version: "2.16"
  name: ${{ name }}
build:
  number: 1
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - if not exist "%PREFIX%/bin/${{ name }}/cpuz_x64.exe" exit /b 1 ))
about:
  homepage: https://www.cpuid.com/softwares/cpu-z.html
  license: Freeware
  summary: System profiling and monitoring tool for Windows
  description: >
    CPU-Z is a freeware system profiling tool that gathers
    information on your CPU, motherboard, memory, and
    other hardware components. It provides real-time monitoring
    and detailed technical specifications.
  documentation: https://www.cpuid.com/softwares/cpu-z.html
  repository: https://www.cpuid.com/
