context:
  name: cpu-z
package:
  version: "2.18"
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  build:
    - selenium
    - toolbox
tests:
  - package_contents:
      bin:
        - ${{ name }}/cpuz_x64

about:
  homepage: https://www.cpuid.com/softwares/cpu-z.html
  summary: System profiling and monitoring tool for Windows
  description: >
    CPU-Z is a freeware system profiling tool that gathers
    information on your CPU, motherboard, memory, and
    other hardware components. It provides real-time monitoring
    and detailed technical specifications.
  documentation: https://www.cpuid.com/softwares/cpu-z.html
  repository: https://www.cpuid.com/
