context:
  name: cpu-z
package:
  version: 2.16
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - if not exist "%PREFIX%/bin/${{ name }}/cpuz_x64.exe" exit /b 1 ))
about:
  homepage: https://www.cpuid.com/softwares/cpu-z.html
