context:
  name: xray
package:
  version: "26.1.31"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script: pwsh -Command "& ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/${{ name }}/${{ name }}${{'.exe' if win}} --help"
about:
  homepage: https://github.com/XTLS/xray-core
  license: GPL-3.0-only
  summary: Xray is a platform for building proxies to bypass network restrictions
  description: >
    Xray is a platform for building proxies to bypass network restrictions and
    improve privacy and security. It supports multiple protocols and is highly
    configurable.
  repository: https://github.com/XTLS/xray-core
