context:
  name: csharpier
  version: "1.3.0"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  - url: https://github.com/belav/csharpier/archive/refs/tags/${{ version }}.tar.gz
build:
  number: 0
  noarch: generic
requirements:
  build:
    - dotnet
    - git
  run:
    - dotnet
tests:
  - script: csharpier --help

about:
  repository: https://github.com/belav/csharpier
extra:
  update: get-version-github -repo "belav/csharpier"
  changelog: get-changelog-github belav/csharpier
