context:
  name: nerdctl
package:
  version: "2.2.1"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
