context:
  name: panda-cad
package:
  version: "5.0.1.8"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - package_contents:
      bin:
        - ${{ name }}/PandaCADViewer
