context:
  name: panda-cad
  version: "5.0.1.8"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://www.intrsio.com/downloadFile.jsp?fileName=PandaCAD-x64-v${{ version }}-Setup.exe
  file_name: ${{ name }}.exe
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1
tests:
  - package_contents:
      bin:
        - ${{ name }}/PandaCADViewer
