context:
  name: peazip
package:
  version: "10.7.0"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script:
      - pwsh -Command "Test-Path ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/${{ name }}/pea${{'.exe' if win}}"

about:
  homepage: https://peazip.github.io
  license: LGPL-3.0-or-later
  summary: Free and open-source file archiver utility
  description: >
    PeaZip is a cross-platform file archiver and file manager supporting
    over 200 archive formats, including ZIP, 7Z, RAR, and TAR. It provides
    a graphical interface for file compression, extraction, and encryption,
    as well as advanced features such as two-factor authentication and
    secure file deletion.
  documentation: https://peazip.github.io/peazip-help.html
  repository: https://github.com/peazip/PeaZip
