package:
  version: 10.3.0
  name: peazip
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-peazip.ps1
tests:
- script:
  - pwsh -c 'test-path $env:PREFIX/bin/peazip/pea.exe'
