context:
  name: tombi
  version: "1.2.4"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/tombi-toml/tombi/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 0
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
tests:
  - package_contents:
      bin:
        - ${{ name }}
about:
  repository: https://github.com/tombi-toml/tombi

extra:
  update: get-version-github -repo "tombi-toml/tombi"
  changelog: get-changelog-github -repo "tombi-toml/tombi"
