context:
  name: cargo-llvm-lines
package:
  version: "0.4.45"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script:
      - pwsh -Command "& ${{'$env:PREFIX' if win else 'PREFIX'}}/bin/${{ name }}${{'.exe' if win}} --help"
about:
  homepage: https://github.com/kbknapp/cargo-llvm-lines
  license: MIT
  summary: Analyze Rust binaries to see LLVM IR code size per function
  description: >
    cargo-llvm-lines is a Cargo subcommand that analyzes Rust
    binaries at the LLVM IR level, showing which functions
    contribute most to code size. It helps developers optimize
    binary size by identifying heavy functions.
  documentation: https://github.com/kbknapp/cargo-llvm-lines#usage
  repository: https://github.com/kbknapp/cargo-llvm-lines
