context:
  name: cargo-llvm-lines
package:
  version: 0.4.44
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-${{ name }}.ps1
about:
  homepage: https://github.com/kbknapp/cargo-llvm-lines
  license: MIT
  summary: Analyze Rust binaries to see LLVM IR code size per function
  description: >
    cargo-llvm-lines is a Cargo subcommand that analyzes Rust
    binaries at the LLVM IR level, showing which functions
    contribute most to code size. It helps developers optimize
    binary size by identifying heavy functions.
  documentation: https://github.com/kbknapp/cargo-llvm-lines#usage
  repository: https://github.com/kbknapp/cargo-llvm-lines