context:
  name: opencolorio
  version: "2.5.1"
recipe:
  version: "2.5.1"
  name: ${{ name }}
source:
  url: https://github.com/AcademySoftwareFoundation/OpenColorIO/archive/refs/tags/v${{ version }}.tar.gz
outputs:
  - staging:
      name: opencolorio-build
    build:
      script:
        interpreter: powershell
        file: build-opencolorio.ps1
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake 3.*
        - ninja
      host:
        - expat
        - imath
        - lcms2
        - ${{ 'minizip' if not osx }}
        - pystring-dev
        - yaml-cpp
        - zlib

  - package:
      name: opencolorio-rt
    inherit: ${{ name }}-build
    requirements:
      run_exports:
        - ${{ pin_subpackage('opencolorio-rt', upper_bound='x.x') }}
    build:
      number: 1
      files:
        - if: osx
          then: lib/*.dylib
        - if: linux
          then: lib/*.so*
        - if: win
          then:
            - Library/*.lib
            - Library/bin/*.dll
    tests:
      - package_contents:
          lib:
            - ${{ 'OpenColorIO*' if win }}
            - ${{ 'libOpenColorIO' if unix }}

  - package:
      name: opencolorio-dev
    inherit: ${{ name }}-build
    requirements:
      host:
        - opencolorio-rt
      run_exports:
        - ${{ pin_subpackage('opencolorio-rt', upper_bound='x.x') }}
    build:
      number: 2

  - package:
      name: opencolorio-app
    inherit: ${{ name }}-build
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake 3.*
        - ninja
      host:
        - expat
        - imath
        - lcms2
        - ${{ 'minizip' if not osx }}
        - pystring-dev
        - yaml-cpp
        - zlib
        - openexr
        - opencolorio-dev
    build:
      number: 2
      script:
        interpreter: powershell
        file: build-opencolorio-app.ps1
    tests:
      - package_contents:
          bin:
            - ocioarchive
            - ociocheck
            - ociochecklut
            - ociobakelut
            - ocioconvert
            - ociocpuinfo
            - ociolutimage
            - ociomakeclf
            - ociomergeconfigs
            - ocioperf
            - ociowrite
