context:
  name: crystal-disk-info
package:
  version: 9.6.3
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - if not exist "%PREFIX%/bin/${{ name }}/DiskInfo64S.exe" exit /b 1 ))
about:
  homepage: https://crystalmark.info/en/download
