context:
  name: uutils-diffutils
  version: "0.5.0"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/uutils/diffutils/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 2
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
tests:
  - package_contents:
      bin:
        - diffutils
about:
  license: MIT
  repository: https://github.com/uutils/diffutils

extra:
  update: get-version-github uutils/diffutils
