context:
  name: jq
package:
  version: 1.8.1
  name: ${{ name }}
build:
  number: 5
  script:
    interpreter: powershell
    file: build.ps1
tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help

about:
  homepage: https://jqlang.github.io/jq
  license: MIT
  summary: A lightweight and flexible command-line JSON processor
  description: >
    jq is a lightweight and flexible command-line JSON processor.
    It allows you to slice, filter, map, and transform structured
    JSON data with ease, directly from your shell.
  documentation: https://jqlang.github.io/jq/manual
  repository: https://github.com/jqlang/jq
