context:
  name: jq
package:
  version: 1.7.1
  name: ${{ name }}
build:
  number: 3
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
- script:
  - '%PREFIX%/bin/${{ name }}/${{ name }}.exe --help'
about:
  description: |
    [dependencies]
    ${{ name }} = "*"
    [exposed]
    ${{ name }} = "bin/${{ name }}/${{ name }}"
