context:
  version: 1.7.1
package:
  version: ${{ version }}
  name: jq
build:
  number: 2
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-jq.ps1
tests:
- script:
  - '%PREFIX%/bin/jq/jq.exe --help'
