context:
  name: jq
package:
  version: 1.8.1
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - "%PREFIX%/bin/${{ name }}.exe --help"

about:
  homepage: https://jqlang.github.io/jq
  license: MIT
  license_file: COPYING
  summary: A lightweight and flexible command-line JSON processor
  description: >
    jq is a lightweight and flexible command-line JSON processor. 
    It allows you to slice, filter, map, and transform structured 
    JSON data with ease, directly from your shell.
  documentation: https://jqlang.github.io/jq/manual
  repository: https://github.com/jqlang/jq
