context:
  name: hwinfo
package:
  version: "8.34"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script: pwsh -Command "Resolve-Path ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/${{ name }}/HWiNFO64${{'.exe' if win}}"

about:
  homepage: https://www.hwinfo.com
  summary: Comprehensive hardware analysis and monitoring tool
  description: >
    HWiNFO is a professional hardware information and diagnostic
    tool for Windows. It provides detailed information about
    system components, real-time monitoring of sensors, and
    reporting features for troubleshooting and performance analysis.
  documentation: https://www.hwinfo.com/documentation/
  repository: https://www.hwinfo.com/
