context:
  name: microsandbox
  version: "0.3.12"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  - url: https://github.com/zerocore-ai/microsandbox/archive/refs/tags/v${{ version }}.tar.gz
    patches:
      - vendored-dbus.patch
build:
  number: 0
requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - pkg-config
  host:
    - if: linux
      then:
        - openssl
        - libcap-ng-dev
tests:
  - package_contents:
      bin:
        - msb
  - script:
      - msb --help
      - msb run --help
      - msb pull python:alpine
about:
  repository: https://github.com/zerocore-ai/microsandbox
