context:
  name: rumqttd
package:
  version: "0.20.0"
  name: ${{ name }}
build:
  number: 4
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - if: linux
      then:
        - rust
        - c-compiler
tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
