context:
  name: aria2

package:
  version: 1.37.0
  name: ${{ name }}
build:
  number: 7
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script:
      - pwsh -Command "& ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/${{ name }}c${{'.exe' if win}} --help"

about:
  homepage: https://aria2.github.io
  license: GPL-2.0-or-later
  summary: Lightweight multi-protocol & multi-source command-line download utility
  description: >
    aria2 is a lightweight multi-protocol and multi-source command-line
    download utility. It supports HTTP, HTTPS, FTP, SFTP, BitTorrent,
    and Metalink. aria2 can download a file from multiple sources and
    protocols, maximizing download speed and reliability.
  documentation: https://aria2.github.io/manual/en/html
  repository: https://github.com/aria2/aria2
