context:
  version: 1.37.0
package:
  version: ${{ version }}
  name: aria2

build:
  number: 1
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-aria2.ps1

tests:
- script:
  - aria2c --help
