context:
  name: aria2

package:
  version: 1.37.0
  name: ${{ name }}
build:
  number: 3
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
- script:
  - '%PREFIX%/bin/${{ name }}/${{ name }}c.exe --help'
about:
  description: |
    [dependencies]
    ${{ name }} = "*"
    [exposed]
    ${{ name }}c = "bin/${{ name }}/${{ name }}c"
