context:
  name: upx
package:
  version: 5.0.2
  name: ${{ name }}
build:
  number: 1
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script: pwsh -Command "& ${{'$env:PREFIX' if win else 'PREFIX'}}/bin/${{ name }}${{'.exe' if win}} --help"
about:
  homepage: https://upx.github.io
  license: GPL-2.0-or-later
  summary: Ultimate Packer for Executables
  description: >
    UPX (Ultimate Packer for Executables) is a free, portable,
    extendable, high-performance executable packer. It compresses
    and decompresses executable files for multiple platforms,
    reducing file size while preserving functionality.
  documentation: https://upx.github.io/
  repository: https://github.com/upx/upx
