context:
  name: blender
package:
  version: 4.5.3
  name: ${{ name }}
build:
  number: 1
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - if not exist "%PREFIX%/bin/${{ name }}/${{ name }}.exe" exit /b 1 ))
about:
  homepage: https://www.blender.org
  license: GPL-3.0-or-later
  summary: Free and open source 3D creation suite
  description: >
    Blender is the free and open source 3D creation suite.
    It supports the entirety of the 3D pipeline including
    modeling, rigging, animation, simulation, rendering,
    compositing, motion tracking, and video editing.
  documentation: https://docs.blender.org/manual/en/latest/
  repository: https://projects.blender.org/blender/blender
