context:
  name: cinebench
package:
  version: 2024
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - if not exist "%PREFIX%/bin/${{ name }}/Cinebench.exe" exit /b 1 ))
about:
  repository: https://github.com/${{ name }}/${{ name }}
