context:
  version: 7.1.1.44
package:
  name: imagemagick
  version: ${{ version }}

build:
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build.ps1
  number: 0
tests:
- script:
  - magick --help
