context:
  name: imagemagick

package:
  name: ${{ name }}
  version: 7.1.1.46

build:
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
  number: 4
tests:
  - script:
      - "%PREFIX%/bin/${{ name }}/magick.exe --help"
about:
  repository: https://github.com/ImageMagick/ImageMagick
  description: |
    [exposed]

    magick = "bin/${{ name }}/magick"
