context:
  name: imagemagick

package:
  name: ${{ name }}
  version: 7.1.2.3

build:
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
  number: 0
tests:
  - script:
      - "%PREFIX%/bin/${{ name }}/magick.exe --help"
about:
  homepage: https://imagemagick.org
  license: Apache-2.0
  summary: Command-line image processing and conversion tool
  description: >
    ImageMagick is a free and open-source software suite for
    creating, editing, composing, or converting bitmap images.
    It supports over 200 image formats and provides tools for
    resizing, cropping, drawing, filtering, and text annotation.
  documentation: https://imagemagick.org/script/index.php
  repository: https://github.com/ImageMagick/ImageMagick
