context:
  version: 7.1.1.44
package:
  name: imagemagick
  version: ${{ version }}

build:
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-imagemagick.ps1
  number: 1
tests:
- script:
  - '%PREFIX%/bin/imagemagick/magick.exe --help'
