context:
  name: oiiotool

package:
  name: ${{ name }}
  version: 3.0.1.0

build:
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
  number: 0

tests:
  - script:
      - if: win
        then:
          "%PREFIX%/bin/${{ name }}/oiiotool.exe --help"
      - if: unix
        then:
          "$PREFIX/bin/${{ name }}/oiiotool --help"
    

about:
  repository: https://github.com/AcademySoftwareFoundation/OpenImageIO
  description: |
    [exposed]

    ottotool = "bin/${{ name }}/oiiotool"
