context:
  name: pureref
package:
  version: "2.1.0"
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  build:
    - selenium
    - toolbox
    - c-compiler
    - cxx-compiler
tests:
  - package_contents:
      bin:
        - ${{ name }}/PureRef

about:
  homepage: https://www.pureref.com
  summary: Lightweight reference image organizer for artists
  description: >
    PureRef is a lightweight application that allows artists
    to organize and view reference images on an infinite canvas.
    It helps creatives keep visual references accessible without
    cluttering the desktop, supporting drag-and-drop, scaling,
    grouping, and layering of images.
  documentation: https://www.pureref.com/help
  repository: https://www.pureref.com
