package:
  version: "2.0.3"
  name: pureref
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%/build-pureref.ps1
tests:
  - script:
      - pwsh -Command "Test-Path $env:PREFIX/bin/${{ name }}/PureRef${{'.exe' if win}}"
about:
  homepage: https://www.pureref.com
  summary: Lightweight reference image organizer for artists
  description: >
    PureRef is a lightweight application that allows artists
    to organize and view reference images on an infinite canvas.
    It helps creatives keep visual references accessible without
    cluttering the desktop, supporting drag-and-drop, scaling,
    grouping, and layering of images.
  documentation: https://www.pureref.com/help
  repository: https://www.pureref.com
