context:
  name: v2rayn
package:
  version: "7.18.0"
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1
tests:
  - package_contents:
      bin:
        - ${{ name }}/v2rayN
