context:
  name: v2rayn
package:
  version: "7.22.3"
  name: ${{ name }}
build:
  number: 1
  script:
    interpreter: powershell
    file: build.ps1
tests:
  - package_contents:
      bin:
        - ${{ name }}/v2rayN

extra:
  update: get-version-github -repo "2dust/v2rayN"
  changelog: get-changelog-github -repo "2dust/v2rayN"
