context:
  name: pyxis-py
  version: "0.0.41"
package:
  version: "0.0.41"
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/pyxis/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 1
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python 3.13.*
    - pip
  run:
    - python >= 3.13
    - lazy-loader
    - numpy
    - scipy

tests:
  - python:
      imports:
        - pyxis
