context:
  name: pyxis-py
  version: "0.0.40"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/pyxis/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 1
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - ${{ compiler("rust") }}
    - maturin
  host:
    - python >= 3.13
    - pip
  run:
    - python >= 3.13
    - lazy-loader
    - numpy
    - scipy

tests:
  - python:
      imports:
        - pyxis
