context:
  name: 7-zip
package:
  version: "26.1"
  name: ${{ name }}
build:
  number: 1
  script:
    - if: win
      then: mkdir "%PREFIX%\bin";copy "%BUILD_PREFIX%\bin\7zz.exe" "%PREFIX%\bin\7z.exe"
      else: mkdir $PREFIX/bin && cp "$BUILD_PREFIX/bin/7zz" "$PREFIX/bin/7z"
requirements:
  build:
    - 7zip
tests:
  - package_contents:
      bin:
        - 7z
  - script: 7z --help
about:
  license: LGPL-2.1-or-later AND LicenseRef-LGPL-2.1-or-later-with-unRAR-restriction
  summary: 7-Zip is a file archiver with a high compression ratio.
  homepage: https://www.7-zip.org/
  repository: https://github.com/ip7z/7zip
extra:
  update: |
    [Version](get-version-conda-forge 7zip)
  changelog: get-changelog-github ip7z/7zip
