context:
  name: 7-zip
package:
  version: "26.0"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - 7zip
tests:
  - package_contents:
      bin:
        - 7z
  - script: 7z --help
