context:
  name: pystring
  version: "1.1.5"
  number: 0
recipe:
  version: ${{ version }}
  name: ${{ name }}
source:
  - url: https://github.com/imageworks/pystring/archive/refs/tags/v${{ version }}.tar.gz
outputs:
  - staging:
      name: pystring-build
    build:
      script:
        interpreter: ${{ "powershell" if win else "bash" }}
        file: build-pystring.${{"ps1" if win else "sh"}}
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake 3.*
        - ninja
  - package:
      name: pystring-rt
    inherit: pystring-build
    build:
      number: ${{ number }}
      files:
        - if: osx
          then: lib/*.dylib
        - if: linux
          then: lib/*.so*
        - if: win
          then:
            - Library/*.lib
            - Library/bin/*.dll
    requirements:
      run_exports:
        - ${{ pin_subpackage('pystring-rt', upper_bound='x.x') }}
    tests:
      - package_contents:
          lib:
            - pystring

  - package:
      name: pystring-dev
    inherit: pystring-build
    build:
      number: ${{ number }}
    requirements:
      host:
        - pystring-rt
      run_exports:
        - ${{ pin_subpackage('pystring-rt', upper_bound='x.x') }}
    tests:
      - package_contents:
          include:
            - pystring.h
about:
  repository: https://github.com/imageworks/pystring
