context:
  name: pystring
  version: "1.1.4"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  - url: https://github.com/imageworks/pystring/archive/refs/tags/v${{ version }}.tar.gz
    patches:
      - fix_cmake.patch
build:
  number: 10
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake 3.*
    - ninja
tests:
  package_contents:
    lib:
      - pystring
about:
  repository: https://github.com/imageworks/pystring
