context:
  name: mqttui
  version: "0.22.1"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/EdJoPaTo/mqttui/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 4
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - if: linux
      then:
        - rust
        - c-compiler
tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
