context:
  name: mqttui
  version: "0.22.1"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/EdJoPaTo/mqttui/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 5
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
