package:
  version: 3.68.1
  name: filezilla
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-filezilla.ps1
tests:
- script:
  - if not exist "%PREFIX%/bin/filezilla/filezilla.exe" exit /b 1 ))
