context:
  name: filezilla
package:
  version: 3.68.1
  name: ${{ name }}
build:
  number: 2
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
- script:
  - if not exist "%PREFIX%/bin/${{ name }}/${{ name }}.exe" exit /b 1 ))
about:
  homepage: https://filezilla-project.org/download.php?show_all=1