context:
  name: vs-buildtools
package:
  version: "18"
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1
tests:
  - package_contents:
      bin:
        - vs_BuildTools
