$cmakeArgs = @(
    "-G"
    "Ninja"
    "-DVERBOSE=ON"
    "-DCMAKE_BUILD_TYPE=Release"
    "-DBUILD_DOCS=0"
    "-DBUILD_SHARED_LIBS=1"
    "-DENABLE_INSTALL_testtex=0"
    "-DENABLE_DCMTK=0"
    "-DENABLE_libuhdr=0"
    "-DENABLE_Nuke=0"
    "-DENABLE_Ptex=0"
    "-DENABLE_Python3=0"
    "-DINSTALL_DOCS=0"
    "-DLINKSTATIC=0"
    "-DOIIO_BUILD_TESTS=0"
    "-DUSE_PYTHON=0"
    "-DUSE_QT=0"
    "-DCMAKE_C_FLAGS=/utf-8"
    "-DCMAKE_CXX_FLAGS=/utf-8"
    "-DUSE_SIMD=sse4.2,avx2"
    "-DCMAKE_INSTALL_PREFIX=$ENV:PREFIX/Library"
)
cmake -S . -B build @cmakeArgs
cmake --build build --config Release --target install
