context:
  name: openimageio

package:
  name: ${{ name }}
  version: 3.0.9.1

build:
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
  number: 0

tests:
  - script:
      - "%PREFIX%/bin/${{ name }}/oiiotool.exe --help"

about:
  repository: https://github.com/AcademySoftwareFoundation/OpenImageIO
  description: |
    [exposed]

    ottotool = "bin/${{ name }}/oiiotool"
