context:
  name: openimageio
  version: "3.1.11.0"
recipe:
  name: ${{ name }}
  version: "3.1.11.0"
source:
  url: https://github.com/AcademySoftwareFoundation/OpenImageIO/archive/refs/tags/v${{ version }}.tar.gz
outputs:
  - staging:
      name: openimageio-build
    build:
      script:
        interpreter: powershell
        file: build-openimageio.ps1
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake 3.*
        - ninja
        - make

      host:
        - opencolorio
        - bzip2
        - fmt
        - freetype
        - ffmpeg
        - giflib
        - libheif
        - libjpeg-turbo
        - libjxl
        - libpng
        - libraw
        - libtiff
        - libwebp
        - openexr
        - openjpeg
        - libopencv
        - openvdb
        - tbb-devel
        - yaml-cpp
        - zlib

  - package:
      name: openimageio-rt
    inherit: openimageio-build
    requirements:
      run_exports:
        - ${{ pin_subpackage('openimageio-rt', upper_bound='x.x') }}
    build:
      number: 2
      files:
        - ${{ 'Library/' if win }}share/*
        - if: osx
          then: lib/*.dylib
        - if: linux
          then: lib/*.so*
        - if: win
          then:
            - Library/*.lib
            - Library/bin/*.dll

  - package:
      name: openimageio
    inherit: openimageio-build
    requirements:
      host:
        - openimageio-rt
      run_exports:
        - ${{ pin_subpackage('openimageio-rt', upper_bound='x.x') }}
    build:
      number: 2
      files:
        exclude:
          - ${{ 'Library/' if win }}share/*
          - if: osx
            then: lib/*.dylib
          - if: linux
            then: lib/*.so*
          - if: win
            then:
              - Library/*.lib
              - Library/bin/*.dll
    tests:
      - script:
          - oiiotool --help

about:
  homepage: https://openimageio.org
  license: BSD-3-Clause
  summary: Library for reading and writing images
  description: >
    OpenImageIO (OIIO) is an open-source library for reading,
    writing, and processing images. It supports a wide variety
    of image formats and provides utilities for image manipulation,
    texture processing, and metadata handling, commonly used in
    visual effects and animation pipelines.
  documentation: https://openimageio.org/documentation/
  repository: https://github.com/OpenImageIO/oiio
