context:
  name: openimageio
package:
  name:
  version: 3.0.4.0
build:
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
  number: 2
tests:
- script:
  - '%PREFIX%/bin/${{ name }}/oiiotool.exe --help'
about:
  description: |
    [dependencies]
    ${{ name }} = "*"
    [exposed]
    ottotool = "bin/${{ name }}/oiiotool"
