package:
  name: openimageio
  version: 3.0.4.0
build:
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-openimageio.ps1
  number: 1
tests:
- script:
  - '%PREFIX%/bin/openimageio/oiiotool.exe --help'
