context:
  version: 3.0.4.0
package:
  name: openimageio
  version: ${{ version }}
build:
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build.ps1
  number: 0
tests:
- script:
  - oiiotool --help

