context:
  name: openimageio
  version: "3.1.10.0"

package:
  name: ${{ name }}
  version: "3.1.10.0"
source:
  url: https://github.com/AcademySoftwareFoundation/OpenImageIO/archive/refs/tags/v${{ version }}.tar.gz
build:
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
  number: 4
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake 3.*
    - ninja
    - make

  host:
    - opencolorio
    - bzip2
    - ${{ 'dcmtk' if not macos}}
    - fmt
    - freetype
    - ffmpeg
    - giflib
    - libheif
    - libjpeg-turbo
    - libjxl
    - libpng
    - libraw
    - libtiff
    - libwebp
    - openexr
    - openjpeg
    - opencv
    - openvdb
    - tbb-devel
    - yaml-cpp
    - zlib
  run_exports:
    - ${{ pin_subpackage('openimageio', upper_bound='x.x') }}
tests:
  - script:
      - oiiotool --help
about:
  homepage: https://openimageio.org
  license: BSD-3-Clause
  summary: Library for reading and writing images
  description: >
    OpenImageIO (OIIO) is an open-source library for reading,
    writing, and processing images. It supports a wide variety
    of image formats and provides utilities for image manipulation,
    texture processing, and metadata handling, commonly used in
    visual effects and animation pipelines.
  documentation: https://openimageio.org/documentation/
  repository: https://github.com/OpenImageIO/oiio
