tests:
- script:
  - magick --help
package:
  version: ${{ version }}
  name: imagemagick
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build.ps1
context:
  version: 7.1.1.44
source:
  git: https://github.com/ImageMagick/ImageMagick.git

