tests:
- script:
  - magick --help
context:
  version: 7.1.1.44
source:
  git: https://github.com/ImageMagick/ImageMagick.git
build:
  script:
  - then:
    - pwsh -f %RECIPE_DIR%\build.ps1
    if: win
  number: 0
package:
  version: ${{ version }}
  name: imagemagick

