context:
  version: 1.7.0
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %PREFIX%\build.ps1
    - mkdir %PREFIX%\scripts
    - copy %RECIPE_DIR%\jq.exe %PREFIX%\scripts\jq.exe
package:
  name: imagemagick
  version: ${{ version }}
source:
  git: https://github.com/ImageMagick/ImageMagick.git
tests:
- script:
  - magick --help
