context:
  version: 7.1.1.44
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build.ps1
tests:
- script:
  - magick --help
source:
  git: https://github.com/ImageMagick/ImageMagick.git
package:
  version: ${{ version }}
  name: imagemagick

