context:
  name: android-sdk-platform-tools

package:
  version: 36.0.0
  name: ${{ name }}
build:
  number: 3
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
- script:
  - '%PREFIX%/bin/${{ name }}/adb.exe --help'
about:
  homepage: https://developer.android.google.cn/tools/releases/platform-tools?hl=zh-cn#downloads
  description: |
    [dependencies]

    ${{ name }} = "*"


    [exposed]

    adb = "bin/${{ name }}/adb"
