context:
  name: android-sdk-platform-tools

package:
  version: 36.0.0
  name: ${{ name }}
build:
  number: 1
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
- script:
  - '%PREFIX%/bin/${{ name }}/adb.exe --help'
about:
  description: |
    [dependencies]
    ${{ name }} = "*"
    [exposed]
    adb = "bin/${{ name }}/adb"

