context:
  version: 0.28.1
package:
  version: ${{ version }}
  name: android-sdk-platform-tools
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-android-sdk-platform-tools.ps1
tests:
- script:
  - '%PREFIX%/bin/android-sdk-platform-tools/adb.exe --help'
