package:
  version: 35.0.2.12147458
  name: android-sdk-platform-tools
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-android-sdk-platform-tools.ps1
tests:
- script:
  - '%PREFIX%/bin/android-sdk-platform-tools/adb.exe --help'
