context:
  name: android-sdk-platform-tools

package:
  version: 36.0.0
  name: ${{ name }}
build:
  number: 1
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
- script:
  - '%PREFIX%/bin/${{ name }}/adb.exe --help'

about:
  homepage: https://developer.android.com/studio/releases/platform-tools
  license: Apache-2.0
  summary: Android SDK Platform-Tools
  description: >
    Android SDK Platform-Tools includes adb and fastboot, 
    essential command-line tools for communicating with 
    Android devices during development and debugging.
  documentation: https://developer.android.com/studio/command-line

