context:
  name: android-sdk-platform-tools

package:
  version: 36.0.0
  name: ${{ name }}
build:
  number: 1
  script:
    - pwsh -f ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}\build-${{ name }}.ps1
tests:
  - script:
      - pwsh -Command "& ${{'$env:PREFIX' if win else 'PREFIX'}}/bin/${{ name }}/adb${{'.exe' if win}} --help"

about:
  homepage: https://developer.android.com/studio/releases/platform-tools
  license: Apache-2.0
  summary: Android SDK Platform-Tools
  description: >
    Android SDK Platform-Tools includes adb and fastboot,
    essential command-line tools for communicating with
    Android devices during development and debugging.
  documentation: https://developer.android.com/studio/command-line
