context:
  name: android-sdk-platform-tools

package:
  version: "36.0.2"
  name: ${{ name }}
source:
  - if: win
    then:
      url: https://googledownloads.cn/android/repository/platform-tools-latest-windows.zip
  - if: osx
    then:
      url: https://dl.google.com/android/repository/platform-tools-latest-darwin.zip
  - if: linux
    then:
      url: https://dl.google.com/android/repository/platform-tools-latest-linux.zip
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1

tests:
  - package_contents:
      bin:
        - adb
  - script: adb --help
about:
  homepage: https://developer.android.com/studio/releases/platform-tools
  license: Apache-2.0
  summary: Android SDK Platform-Tools
  description: >
    Android SDK Platform-Tools includes adb and fastboot,
    essential command-line tools for communicating with
    Android devices during development and debugging.
  documentation: https://developer.android.com/studio/command-line
