context:
  name: proj
package:
  version: "9.7.0"
  name: ${{ name }}
build:
  number: 0
  script:
    - pwsh -f ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}\build-${{ name }}.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-${{ name }}.ps1
about:
  repository: https://github.com/OSGeo/PROJ
