context:
  name: proj
  version: "9.8.0"
recipe:
  version: "9.8.0"
  name: ${{ name }}
source:
  url: https://github.com/OSGeo/PROJ/archive/refs/tags/${{ version }}.tar.gz
outputs:
  - staging:
      name: proj-build
    build:
      script:
        interpreter: powershell
        file: build-proj.ps1
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake 3.*
        - ninja

      host:
        - sqlite
        - libtiff
        - libcurl

  - package:
      name: proj-rt
    inherit: proj-build
    requirements:
      run_exports:
        - ${{ pin_subpackage('proj-rt', upper_bound='x.x') }}
    build:
      files:
        - if: osx
          then:
            - lib/*.dylib
            - share/proj/*
        - if: linux
          then:
            - lib/*.so*
            - share/proj/*
        - if: win
          then:
            - Library/*.lib
            - Library/bin/*.dll
            - Library/share/proj/*

  - package:
      name: proj-dev
    inherit: proj-build
    requirements:
      host:
        - proj-rt
    build:
      files:
        - ${{ 'Library/' if win }}include/*
        - ${{ 'Library/' if win }}lib/cmake/*
        - ${{ 'Library/' if win }}lib/pkgconfig/*
        - ${{ 'Library/' if win }}share/bash-completion/*
        - ${{ 'Library/' if win }}share/doc/*
        - ${{ 'Library/' if win }}share/man/*
    tests:
      - package_contents:
          include:
            - proj.h

  - package:
      name: proj-app
    inherit: proj-build
    requirements:
      host:
        - proj-rt
    build:
      files:
        - ${{ 'bin/*' if unix }}
        - ${{ 'bin/*.exe' if unix }}
    tests:
      - package_contents:
          bin:
            - cs2cs
            - proj
            - cct
            - geod
            - gie
            - invgeod
            - invproj
      - script: projinfo -s EPSG:2230 -t EPSG:26946

about:
  repository: https://github.com/OSGeo/PROJ
  documentation: https://proj.org/en/stable/
