context:
  name: proj
  version: "9.8.1"
  number: 2
recipe:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/OSGeo/PROJ/archive/refs/tags/${{ version }}.tar.gz
outputs:
  - staging:
      name: proj-build
    build:
      script:
        interpreter: ${{ "powershell" if win else "bash" }}
        file: build-proj.${{ "ps1" if win else "sh" }}
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake 3.*
        - ninja
      host:
        - sqlite
        - libtiff
        - libcurl

  - package:
      name: proj-rt
    inherit: ${{ name }}-build
    requirements:
      run_exports:
        - ${{ pin_subpackage('proj-rt', upper_bound='x.x') }}
    build:
      number: ${{ number }}
      files:
        - if: osx
          then:
            - lib/*.dylib
        - if: linux
          then:
            - lib/*.so*
        - if: win
          then:
            - Library/*.lib
            - Library/bin/*.dll

  - package:
      name: proj-data
    inherit:
      from: ${{ name }}-build
      run_exports: false
    build:
      number: ${{ number }}
      files:
        - ${{ 'Library/' if win }}share/proj

  - package:
      name: proj-app
    inherit: ${{ name }}-build
    requirements:
      run:
        - proj-rt
    build:
      number: ${{ number }}
      files:
        - ${{ 'bin/*' if unix }}
        - ${{ 'Library/bin/*' if win }}
        - ${{ 'Library/' if win }}share/bash-completion/*
        - ${{ 'Library/' if win }}share/man/*
    tests:
      - package_contents:
          bin:
            - cs2cs
            - proj
            - cct
            - geod
            - gie
            - invgeod
            - invproj
      - script: projinfo -s EPSG:2230 -t EPSG:26946

  - package:
      name: proj-dev
    inherit: ${{ name }}-build
    requirements:
      run:
        - proj-rt
        - proj-data
        - proj-app
      run_exports:
        - ${{ pin_subpackage('proj-rt', upper_bound='x.x') }}
    build:
      number: ${{ number }}
    tests:
      - package_contents:
          include:
            - proj.h

about:
  repository: https://github.com/OSGeo/PROJ
  documentation: https://proj.org/en/stable/
