context:
  name: proj
package:
  version: "9.7.1"
  name: ${{ name }}
build:
  number: 5
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - pkg-config
    - openssl
    - make
    - if: Linux
      then:
        - ${{ stdlib('c') }}
about:
  repository: https://github.com/OSGeo/PROJ
