context:
  name: proj
  version: "9.7.1"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/OSGeo/PROJ/archive/refs/tags/${{ version }}.tar.gz
build:
  number: 7
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - c-compiler
    - cxx-compiler
    - cmake 3.*
    - ninja
    - if: win
      then:
        - vs_win-64
  host:
    - sqlite
    - libtiff
    - libcurl
tests:
  - package_contents:
      include:
        - proj.h
      bin:
        - cs2cs
        - proj
        - cct
        - geod
        - gie
        - invgeod
        - invproj
  - script: projinfo -s EPSG:2230 -t EPSG:26946
about:
  repository: https://github.com/OSGeo/PROJ
  documentation: https://proj.org/en/stable/
