package:
  version: 31.0.2
  name: obs-studio
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-obs-studio.ps1
tests:
- script:
  - '%PREFIX%/bin/obs-studio/bin/obs64.exe --help'
