package:
  version: 31.0.2
  name: obs-studio
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-obs-studio.ps1
tests:
- script:
  - pwsh -c 'test-path $env:PREFIX/bin/obs-studio/bin/64bit/obs64.exe'
