context:
  name: obs-studio
package:
  version: 31.0.4
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - if not exist "%PREFIX%/bin/${{ name }}/bin/64bit/obs64.exe" exit /b 1 ))
about:
  repository: https://github.com/obsproject/${{ name }}
