context:
  name: edit
package:
  version: 1.7.1
  name: ${{ name }}
build:
  number: 5
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%/build-${{ name }}.ps1
    - if: linux
      then:
        - pwsh -f $RECIPE_DIR/build-${{ name }}.ps1
tests:
  - script:
      - if: win
        then:
          - "%PREFIX%/bin/${{ name }}.exe --help"
      - if: linux
        then:
          - "$PREFIX/bin/${{ name }} --help"
about:
  repository: https://github.com/microsoft/${{ name }}
  description: |
    [exposed]

    ${{ name }} = "${{ name }}"
