context:
  name: edit
package:
  version: 1.0.0
  name: ${{ name }}
build:
  number: 1
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%/build-${{ name }}.ps1
    - if: linux
      then:
        - pwsh -f $RECIPE_DIR/build-${{ name }}.ps1
tests:
  - script:
      - if: win
        then:
          - "%PREFIX%/bin/${{ name }}.exe -h"
      - if: linux
        then:
          - "ls -l $PREFIX/bin/ && bash $PREFIX/bin/${{ name }} -h"
about:
  repository: https://github.com/microsoft/${{ name }}
  description: |
    [exposed]

    ${{ name }} = "${{ name }}"
