context:
  name: edit
package:
  version: "1.2.1"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script: pwsh -Command "& ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/${{ name }}${{'.exe' if win}} --help"
about:
  homepage: https://github.com/microsoft/edit
  license: MIT
  summary: Lightweight, modeless command-line text editor for Windows
  description: >
    Edit is a small, modern command-line text editor for Windows 11,
    designed to be intuitive and user-friendly. It offers a modeless
    interface, making it easier for users unfamiliar with modal editors
    like Vim. With a footprint under 250KB, it integrates seamlessly
    into the Windows environment.
  documentation: https://learn.microsoft.com/en-us/windows/edit/
  repository: https://github.com/microsoft/edit
