context:
  name: espflash
package:
  version: "4.2.0"
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-${{ name }}.ps1
tests:
  - script:
      - pwsh -Command "&$env:PREFIX/bin/${{ name }}${{'.exe' if win}} --help"
