context:
  name: espflash
package:
  version: "4.3.0"
  name: ${{ name }}
build:
  number: 4
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
about:
  homepage: https://github.com/esp-rs/espflash
  summary: A flashing tool for ESP32 and ESP8266 boards written in Rust
  description: >
    espflash is a command-line tool designed for flashing firmware onto ESP32 and ESP8266 microcontroller boards. Written in Rust, it offers a fast and reliable way to upload compiled code to these popular IoT devices. espflash supports various features such as automatic detection of connected boards, configuration of flash parameters, and verification of flashed data, making it an essential tool for developers working with ESP-based projects.
  license: MIT
  repository: https://github.com/esp-rs/espflash
