name: main
inputs:
  pkg:
    description: "package"

runs:
  using: "composite"
  steps:
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        run-install: false

    - name: login
      run: pixi auth login prefix.dev --token ${{secrets.PREFIX_TOKEN}}

    - name: main
      id: main
      env:
        GH_TOKEN: ${{ github.token }}
      run: ./packages/${{inputs.pkg}}/ci-${{inputs.pkg}}.ps1
      shell: pwsh

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.pkg}}
        path: ./packages/${{inputs.pkg}}/output/win-64

    - name: publish
      if: ${{ steps.main.outputs.update != 'true' && github.event_name != 'pull_request' && github.ref_name=='main'}}
      run: |
        ./scripts/publish.ps1 -pkg ${{inputs.pkg}}
      shell: pwsh
      continue-on-error: true

    - name: Create pull request
      if: ${{ steps.main.outputs.update == 'true' && github.event_name != 'pull_request' && !cancelled()}}
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ github.token }}
        commit-message: "chore: update `${{inputs.pkg}}` from `${{ steps.main.outputs.current-version}}` to `${{ steps.main.outputs.latest-version}}`"
        title: "chore: update `${{inputs.pkg}}` from `${{ steps.main.outputs.current-version}}` to `${{ steps.main.outputs.latest-version}}`"
        branch: update-${{inputs.pkg}}
        base: main
        labels: action
        delete-branch: true
        assignees: Glatzel
        draft: true
