name: main
inputs:
  args:
    description: "ci.ps1 args"
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        run-install: false

    - name: main
      id: main
      env:
        GH_TOKEN: ${{ github.token }}
      run: ./packages/${{github.job}}/ci-${{github.job}}.ps1 ${{inputs.args}}
      shell: pwsh

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{github.job}}
        path: ./packages/${{github.job}}/output/win-64

    - name: publish
      if: ${{ steps.main.outputs.update != 'true' && github.event_name != 'pull_request'}}
      run: |
        ./scripts/publish.ps1 -pkg ${{github.job}}
      shell: pwsh
      continue-on-error: true

    - name: Create pull request
      if: ${{ steps.main.outputs.update == 'true' && github.event_name != 'pull_request' && !cancelled()}}
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ github.token }}
        commit-message: "chore: update `${{github.job}}` to `${{ steps.main.outputs.latest-version}}`"
        title: "chore: update `${{github.job}}` to `${{ steps.main.outputs.latest-version}}`"
        branch: update-${{github.job}}
        base: main
        labels: action
        delete-branch: true
        assignees: Glatzel
        draft: true
