name: main
inputs:
  pkg:
    description: "pkg"
  args:
    description: "ci.ps1 args"
    default: ''
  publish:
    description: "upload package"

runs:
  using: "composite"
  steps:
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        run-install: false

    - name: ci
      env:
        GH_TOKEN: ${{ github.token }}
      run: ./packages/${{inputs.pkg}}/ci-${{inputs.pkg}}.ps1 ${{inputs.args}}
      shell: pwsh

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.pkg}}
        path: ./packages/${{inputs.pkg}}/output/win-64

    - name: publish
      if: ${{inputs.publish=='true'}}
      run: |
        ./scripts/publish.ps1 -pkg ${{inputs.pkg}}
      shell: pwsh
      continue-on-error: true
