$ROOT = git rev-parse --show-toplevel
. $ROOT/scripts/util.ps1
if ($IsWindows) {
    $env:CMAKE_INSTALL_PREFIX = "$ENV:PREFIX/Library"
}
else {
    $env:CMAKE_INSTALL_PREFIX = "$ENV:PREFIX"
}
$cmakeArgs = @(
    "-G"
    "Ninja"
    "-DCMAKE_BUILD_TYPE=Release"
    "-DNANOVDB_BUILD_BENCHMARK=OFF"
    "-DNANOVDB_BUILD_EXAMPLES=OFF"
    "-DNANOVDB_BUILD_TOOLS=OFF"
    "-DNANOVDB_BUILD_UNITTESTS=OFF"
    "-DNANOVDB_USE_OPENVDB=OFF"
    "-DOPENVDB_BUILD_AX_BINARIES=OFF"
    "-DOPENVDB_BUILD_AX_GRAMMAR=ON"
    "-DOPENVDB_BUILD_AX_UNITTESTS=OFF"
    "-DOPENVDB_BUILD_AX=ON"
    "-DOPENVDB_BUILD_BINARIES=OFF"
    "-DOPENVDB_BUILD_DOCS=OFF"
    "-DOPENVDB_BUILD_HOUDINI_PLUGIN=OFF"
    "-DOPENVDB_BUILD_MAYA_PLUGIN=OFF"
    "-DOPENVDB_BUILD_NANOVDB=OFF"
    "-DOPENVDB_BUILD_PYTHON_MODULE=OFF"
    "-DOPENVDB_BUILD_UNITTESTS=OFF"
    "-DOPENVDB_BUILD_VDB_LOD=OFF"
    "-DOPENVDB_BUILD_VDB_PRINT=OFF"
    "-DOPENVDB_BUILD_VDB_RENDER=OFF"
    "-DOPENVDB_BUILD_VDB_VIEW=OFF"
)
cmake -S . -B build @cmakeArgs
cmake --build build --config Release --target install
