context:
  name: pyxis-cli
package:
  version: 0.0.39
  name: ${{ name }}
build:
  number: 1
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script: pwsh -Command "& ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/pyxis${{'.exe' if win}} --help"
