context:
  name: pyxis-cli
  version: "0.0.41"
package:
  version: "0.0.41"
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/pyxis/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 3
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - pkg-config
    - proj
  host:
    - proj
    - if: osx
      then:
        - libiconv
    - if: linux
      then:
        - libstdcxx
        - libudev
tests:
  - script: pyxis --help
