context:
  name: pyxis-cli
  version: "0.0.41"
package:
  version: "0.0.41"
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/pyxis/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 2
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - pkg-config
    - proj
    - ${{ 'rust' if linux }}
  host:
    - proj
    - if: osx
      then:
        - libiconv
    - if: linux
      then:
        - libstdcxx
        - libudev
tests:
  - script: pyxis --help
