context:
  name: pyxis-cli
  version: "0.0.42"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/pyxis/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 2
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - pkg-config
    - proj-dev
  host:
    - proj-rt
tests:
  - script: pyxis --help
