context:
  name: pyxis-cli
  version: "0.0.40"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/pyxis/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 3
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - ${{ compiler("rust") }}
    - pkg-config
    - proj
  host:
    - libstdcxx
    - libudev
  run:
    - if: linux
      then:
        - libstdcxx
        - libudev
tests:
  - script: pyxis --help
