context:
  name: dnc
package:
  version: "18.2.2"
  name: ${{ name }}
build:
  number: 1
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  run:
    - aria2
tests:
  - script:
      interpreter: powershell
      content: |
        ls "C:/Program Files/Adobe/Adobe DNG Converter/"
        Test-Path "C:/Program Files/Adobe/Adobe DNG Converter/Adobe DNG Converter.exe"
        (Get-Item "C:/Program Files/Adobe/Adobe DNG Converter/Adobe DNG Converter.exe").VersionInfo.ProductVersion
        curl http://www.rawsamples.ch/raws/canon/RAW_CANON_EOS-M.CR2 -o RAW_CANON_EOS-M.CR2
        & "C:/Program Files/Adobe/Adobe DNG Converter/Adobe DNG Converter.exe" -c "$(resolve-path ./RAW_CANON_EOS-M.CR2)"
