context:
  name: easytier
  version: "2.4.5"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  - url: https://github.com/EasyTier/EasyTier/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 1
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - ${{ compiler('rust') }}
    - if: linux
      then:
        - c-compiler
        - cxx-compiler
        - clang
        - libclang
  host:
    - ${{ libprotobuf if unix}}
tests:
  - package_contents:
      bin:
        - ${{ name }}-core
        - ${{ name }}-cli
  - script: ${{ name }}-core --help
about:
  repository: https://github.com/EasyTier/EasyTier
