context:
  name: easytier
  version: "2.4.5"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  # https://npcap.com/#download
  - url: https://npcap.com/dist/npcap-sdk-1.16.zip
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - rust
    - if: linux
      then:
        - gcc 10.*
        - gxx 10.*
  host:
    - if: unix
      then:
        - libprotobuf
  run:
    - if: unix
      then:
        - libprotobuf
tests:
  - package_contents:
      bin:
        - ${{ name }}-core
        - ${{ name }}-cli
  - script: ${{ name }}-core --help
about:
  repository: https://github.com/EasyTier/EasyTier
