context:
  name: easytier
package:
  version: "2.4.5"
  name: ${{ name }}
build:
  number: 0
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script: pwsh -Command "& ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/${{ name }}-core${{'.exe' if win}} --help"
about: 
  homepage: https://github.com/yourusername/easytier
  license: MIT OR Apache-2.0
  summary: EasyTier is a tool for managing storage tiers
  description: >
    EasyTier is a tool designed to help manage and optimize storage tiers in a system,
    providing efficient data placement and movement across different storage media.
  repository: https://github.com/yourusername/easytier
