context:
  name: blender-benchmark
package:
  version: 3.2.0
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - "%PREFIX%/bin/${{ name }}/benchmark-launcher-cli.exe --help"
about:
  homepage: https://opendata.blender.org/
  description: |
    [exposed]

    ${{ name }} = "bin/${{ name }}/benchmark-launcher-cli"
