context:
  name: blender-benchmark
package:
  version: 3.2.0
  name: ${{ name }}
build:
  number: 1
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - selenium
tests:
  - script:
      - pwsh -Command "& ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/${{ name }}/benchmark-launcher-cli${{'.exe' if win}} --help"
about:
  homepage: https://opendata.blender.org
  license: GPL-3.0-or-later
  summary: Blender Benchmark tool for measuring 3D rendering performance
  description: >
    Blender Benchmark is a performance testing tool that uses
    Blender to measure the rendering speed of your system.
    Results can be compared and shared on Blender Open Data,
    helping users evaluate hardware performance for 3D workloads.
  documentation: https://opendata.blender.org/about
  repository: https://projects.blender.org/blender/blender-benchmark
