context:
  name: cargo-binutils
package:
  version: "0.4.0"
  name: ${{ name }}
build:
  number: 5
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
tests:
  - script: cargo-size --help

about:
  homepage: https://github.com/rust-embedded/cargo-binutils
  license: MIT OR Apache-2.0
  summary: Cargo subcommands for working with GNU binutils
  description: >
    A collection of Cargo subcommands for working with GNU binutils tools such as objdump, nm, and size.
  repository: https://github.com/rust-embedded/cargo-binutils
