context:
  name: cargo-binutils
package:
  version: "0.4.0"
  name: ${{ name }}
build:
  number: 4
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
requirements:
  build:
    - if: linux
      then:
        - c-compiler
        - cxx-compiler
tests:
  - script: cargo-size --help

about:
  homepage: https://github.com/rust-embedded/cargo-binutils
  license: MIT OR Apache-2.0
  summary: Cargo subcommands for working with GNU binutils
  description: >
    A collection of Cargo subcommands for working with GNU binutils tools such as objdump, nm, and size.
  repository: https://github.com/rust-embedded/cargo-binutils
