context:
  name: duckdb-cli
  version: "1.5.2"
package:
  version: ${{version}}
  name: ${{ name }}
source:
  - url: https://github.com/duckdb/duckdb/archive/refs/tags/v${{ version }}.tar.gz

build:
  number: 0
requirements:
  build:
    - ${{compiler("c")}}
    - ${{compiler("cxx")}}
    - ${{compiler("cxx")}}
    - ${{ stdlib('c') }}
    - ${{"make" if unix}}
    - cmake
    - ninja
    - python

tests:
  - package_contents:
      bin:
        - duckdb

about:
  repository: https://github.com/duckdb/duckdb

extra:
  update: get-version-github -repo "duckdb/duckdb"
  changelog: get-changelog-github "duckdb/duckdb"
