context:
  name: sys-baidu-netdisk
package:
  version: "3.2.0.4351"
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    content: |
      new-item $env:PREFIX/Scripts -itemType Directory -Force -ErrorAction SilentlyContinue
      Copy-Item $env:RECIPE_DIR/install-${{name}}.ps1 $env:PREFIX/Scripts/
requirements:
  run:
    - sys-install
