context:
  name: rustup-init
  version: "1.29.0"
package:
  version: "1.29.0"
  name: ${{ name }}
source:
  url: https://github.com/rust-lang/rustup/archive/refs/tags/${{ version }}.tar.gz
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - pkg-config
  host:
    - ${{ 'openssl' if linux}}
tests:
  - package_contents:
      bin:
        - rustup-init
  - script:
      interpreter: powershell
      content: |
        rustup-init -y --default-toolchain stable --profile minimal
        & $HOME/rustup components add clippy
        & $HOME/rustup targets add riscv32imc-unknown-none-elf
about:
  repository: https://github.com/rust-lang/rustup
