context:
  name: cloudflared
package:
  version: 2025.8.1
  name: ${{ name }}
build:
  number: 2
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-${{ name }}.ps1
about:
  repository: https://github.com/cloudflare/${{ name }}
  description: |
    [exposed]

    ${{ name }} = "${{ name }}"
