context:
  name: cloudflared
package:
  version: "2025.10.1"
  name: ${{ name }}
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-${{ name }}.ps1
about:
  homepage: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/
  license: Apache-2.0
  summary: Cloudflare Tunnel client
  description: >
    cloudflared is a command-line tool that establishes secure
    tunnels to Cloudflare's network. It allows exposing local
    services to the internet without opening firewall ports,
    supporting features like Argo Tunnel and Zero Trust access.
  documentation: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/
  repository: https://github.com/cloudflare/cloudflared
