context:
  version: 6.13.2
package:
  name: nuget
  version: ${{ version }}
build:
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-nuget.ps1
  number: 1
tests:
- script:
  - '%PREFIX%/bin/nuget/nuget.exe help'
