context:
  name: nuget
  version: "7.3.0"
package:
  name: ${{ name }}
  version: "7.3.0"
source:
  url: https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
build:
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
  number: 0
tests:
  - script: ${{ name }} help
about:
  homepage: https://www.nuget.org
  license: Apache-2.0
  summary: Package manager for .NET
  description: >
    NuGet is the package manager for .NET, providing tools to
    create, share, and consume reusable code packages. It
    simplifies dependency management and versioning for .NET
    projects across multiple platforms.
  documentation: https://docs.microsoft.com/en-us/nuget/
  repository: https://github.com/NuGet/NuGet.Client
