context:
  name: nuget
package:
  name: ${{ name }}
  version: 6.13.2
build:
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
  number: 5
tests:
- script:
  - '%PREFIX%/bin/${{ name }}/${{ name }}.exe help'
about:
  description: |
    [dependencies]
    ${{ name }} = "*"
    [exposed]
    ${{ name }} = "bin/${{ name }}/${{ name }}"