context:
  name: nuget
package:
  name: ${{ name }}
  version: 6.14.0
build:
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
  number: 1
tests:
  - script:
      - "%PREFIX%/bin/${{ name }}.exe help"
about:
  repository: https://www.nuget.org/downloads
  description: |
    [exposed]

    ${{ name }} = "${{ name }}"
