context:
  version: 6.13.2

package:
  name: nuget
  version: ${{ version }}

tests:
- script:
  - nuget --help

build:
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build.ps1
  number: 0
