context:
  name: orc
  version: "2026.4.3"
package:
  version: ${{ version }}
  name: ${{ name }}
source:
  url: https://github.com/Glatzel/toolbox/archive/refs/tags/v${{ version }}.tar.gz
build:
  number: 5
requirements:
  build:
    - ${{ compiler('rust') }}
tests:
  - script: orc --help
