context:
  name: bat
package:
  version: "0.26.1"
  name: ${{ name }}
build:
  number: 0
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
tests:
  - package_contents:
      bin:
        - ${{name}}
  - script: ${{name}} --help
about:
  repository: https://github.com/sharkdp/bat

extra:
  update: get-version-crateio -name $name
  changelog: get-changelog-github "sharkdp/bat"
