context:
  name: zyperwin
package:
  version: "4.1"
  name: ${{ name }}
build:
  number: 2
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - package_contents:
      bin:
        - ZyperWin++
