context:
  name: zyperwin
package:
  version: "4.1"
  name: ${{ name }}
build:
  number: 2
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - pwsh -Command "Test-Path $env:PREFIX/bin/${{ name }}/ZyperWin++${{'.exe' if win}}"
