context:
  name: zyperwin
package:
  version: "4.1"
  name: ${{ name }}
build:
  number: 2
  script:
    - pwsh -f ${{'$env:RECIPE_DIR'}}\build-${{ name }}.ps1
tests:
  - script:
      - pwsh -Command "Test-Path $env:PREFIX/bin/${{ name }}/ZyperWin++${{'.exe' if win}}"
