context:
  name: zyperwin
package:
  version: "4.1"
  name: ${{ name }}
build:
  number: 2
  script:
    interpreter: powershell
    file: build.ps1
tests:
  - package_contents:
      bin:
        - ZyperWin++
