context:
  name: everything
package:
  version: 1.4.1.1026
  name: ${{ name }}
build:
  number: 0
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
    - if not exist "%PREFIX%/bin/${{ name }}/${{ name }}.exe" exit /b 1 ))
about:
  description: |
    [dependencies]
    ${{ name }} = "*"
    [exposed]
    ${{ name }} = "bin/${{ name }}/${{ name }}"
