context:
  name: rufus
package:
  version: '4.7'
  name: ${{ name }}
build:
  number: 2
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%\build-${{ name }}.ps1
tests:
  - script:
      - if not exist "%PREFIX%/bin/${{ name }}.exe" exit /b 1 ))
about:
  repository: https://github.com/pbatard/rufus
