context:
  name: rufus
package:
  version: "4.13"
  name: ${{ name }}
build:
  number: 0
  script:
    interpreter: powershell
    file: build.ps1
tests:
  - package_contents:
      bin:
        - ${{ name }}
about:
  homepage: https://rufus.ie
  license: GPL-3.0-or-later
  summary: Utility to create bootable USB drives
  description: >
    Rufus is a free and open-source utility that helps format
    and create bootable USB drives, such as USB keys/pendrives,
    memory sticks, etc. It is widely used for creating installation
    media from ISO files for Windows, Linux, and other operating systems.
  documentation: https://rufus.ie/en/
  repository: https://github.com/pbatard/rufus
