name: CI
on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref=='refs/heads/main' && github.sha || github.ref}}
  cancel-in-progress: ${{ github.event_name != 'push'}}
env:
  GITHUB_EVENT_NAME: ${{ github.event_name }}
  GITHUB_REF_NAME: ${{github.ref_name}}
jobs:
  lefthook:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
      pull-requests: write
  dispatch:
    runs-on: ubuntu-slim
    outputs:
      matrix: ${{ steps.matrix_json.outputs.matrix }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: packages_yaml
        if: ${{github.event_name == 'pull_request' || github.event_name == 'push'}}
        run: ./scripts/packages_yaml.ps1
        shell: pwsh

      - id: change
        if: ${{github.event_name == 'pull_request' || github.event_name == 'push'}}
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          json: true
          files_yaml_from_source_file: ./packages.yaml
      - name: matrix_json
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          CHANGED_KEYS: ${{steps.change.outputs.changed_keys}}
        id: matrix_json
        run: ./scripts/matrix_json.ps1
        shell: pwsh

  rattler-build:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    if: ${{needs.dispatch.outputs.matrix != '' }}
    needs: dispatch
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.dispatch.outputs.matrix) }}
    runs-on: ${{ matrix.machine }}
    container:
      image: ${{matrix.container}}
    env:
      TARGET_PLATFORM: ${{ matrix.target_platform }}
    steps:
      - if: ${{matrix.container}}
        run: git config --system --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          run-install: false

      - name: build-recipe-win
        if: ${{ contains(matrix.machine, 'windows') }}
        id: build-win
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          $ROOT = git rev-parse --show-toplevel
          . $ROOT/scripts/util.ps1
          build-recipe
        shell: pwsh
        working-directory: ./packages/${{matrix.pkg}}

      - name: publish-win
        if: ${{ steps.build-win.outputs.action_publish == 'true'&& contains(matrix.machine, 'windows')}}
        run: ./scripts/publish.ps1 -pkg ${{matrix.pkg}}

      - name: build-recipe-unix
        if: ${{ !contains(matrix.machine, 'windows') }}
        id: build-unix
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          ROOT=$(git rev-parse --show-toplevel)
          . "$ROOT/scripts/util.sh"
          build_recipe
        working-directory: ./packages/${{matrix.pkg}}

      - name: publish-unix
        if: ${{ steps.build-unix.outputs.action_publish == 'true' && !contains(matrix.machine, 'windows') }}
        run: ./scripts/publish.sh ${{matrix.pkg}}

  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [lefthook, rattler-build, dispatch]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
