name: manual-build
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Package name"
        type: string
        required: true
      machine:
        description: "machine"
        type: choice
        required: true
        options:
          - windows-latest
          - macos-latest
          - ubuntu-latest
          - ubuntu-24.04-arm
          - ubuntu-slim
      target-platform:
        description: "target-platform"
        type: choice
        required: true
        options:
          - win-64
          - osx-arm64
          - linux-64
          - linux-aarch64
          - noarch
      upload:
        type: boolean
        description: "upload"
        required: true
        default: false
      publish:
        type: boolean
        description: "publish"
        required: true
        default: false
      debug_on_fail:
        type: boolean
        description: "debug on fail"
        required: true
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref}}-${{inputs.name}}-${{inputs.machine}}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  pull-requests: write
env:
  WORKFLOW_NAME: ${{ github.workflow }}
jobs:
  rattler-build:
    runs-on: ${{inputs.machine}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false

      - name: main
        id: main
        env:
          GH_TOKEN: ${{github.token}}
          TARGET_PLATFORM: ${{ inputs.target-platform }}
        run: ./packages/${{inputs.name}}/ci.ps1
        shell: pwsh

      - name: upload
        if: ${{ inputs.upload }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{inputs.name}}-${{inputs.target-platform}}
          path: ./output

      - name: publish
        if: ${{ inputs.publish }}
        run: |
          ./scripts/publish.ps1 -pkg ${{inputs.name}}
        shell: pwsh

      - name: Debug with tmate
        if: ${{failure()&& inputs.debug_on_fail}}
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 # v3.23
