name: manual-build
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Package name"
        type: string
        required: true
      machine:
        description: "machine"
        type: choice
        required: true
        options:
          - windows-latest
          - macos-latest
          - ubuntu-latest
          - ubuntu-24.04-arm
          - ubuntu-slim
      target-platform:
        description: "target-platform"
        type: choice
        required: true
        options:
          - win-64
          - osx-arm64
          - linux-64
          - linux-aarch64
          - noarch
      upload:
        type: boolean
        description: "upload"
        required: true
        default: false
      publish:
        type: boolean
        description: "publish"
        required: true
        default: false
      debug_on_fail:
        type: boolean
        description: "debug on fail"
        required: true
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref}}-${{inputs.name}}-${{inputs.machine}}
  cancel-in-progress: true

permissions:
  id-token: write
env:
  WORKFLOW_NAME: ${{ github.workflow }}
  TARGET_PLATFORM: ${{ inputs.target-platform }}
jobs:
  rattler-build:
    runs-on: ${{inputs.machine}}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          run-install: false

      - name: build-win
        if: ${{ contains(inputs.machine, 'windows') }}
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          $ROOT = git rev-parse --show-toplevel
          . $ROOT/scripts/util.ps1
          build-recipe
        shell: pwsh
        working-directory: ./packages/${{inputs.name}}

      - name: build-unix
        if: ${{ !contains(inputs.machine, 'windows') }}
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          ROOT=$(git rev-parse --show-toplevel)
          . "$ROOT/scripts/util.sh"
          build_recipe
        working-directory: ./packages/${{inputs.name}}

      - name: upload
        if: ${{ inputs.upload }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{inputs.name}}-${{inputs.target-platform}}
          path: ./output

      - name: publish-win
        if: ${{ inputs.publish && contains(inputs.machine, 'windows')}}
        run: ./scripts/publish.ps1 -pkg ${{inputs.name}}

      - name: publish-unix
        if: ${{ inputs.publish && !contains(inputs.machine, 'windows') }}
        run: ./scripts/publish.sh ${{inputs.name}}

      - name: Debug with tmate
        if: ${{failure()&& inputs.debug_on_fail}}
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3.24
