name: rattler build
on:
  workflow_call:
    inputs:
      pkg:
        type: string
        description: "pkg"
    secrets:
      prefix_key:
        required: true
permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          run-install: false
      - name: install pwsh-yaml
        run: Install-Module powershell-yaml -Force
        shell: pwsh

      - name: ci
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./packages/${{inputs.pkg}}/ci.ps1
        shell: pwsh

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.pkg}}
          path: ./packages/${{inputs.pkg}}/output/win-64

      - name: publish
        run: |
          ./scripts/publish.ps1 -pkg ${{inputs.pkg}} -key ${{secrets.prefix_key}}
        shell: pwsh
        continue-on-error: true

      
