name: rattler build
on:
  workflow_call:
    inputs:
      pkg:
        type: string
        description: "pkg"
permissions:
  contents: read
  id-token: write

jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            ./github/**
            ./scripts/**
            ./${{inputs.pkg}}/**

      - name: Set up pixi
        if: ${{github.event_name !='pull_request' || steps.changed.outputs.any_changed == 'true' }}
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false
      - name: install pwsh-yaml
        if: ${{github.event_name !='pull_request' || steps.changed.outputs.any_changed == 'true' }}
        run: Install-Module powershell-yaml -Force
        shell: pwsh

      - name: ci
        if: ${{github.event_name !='pull_request' || steps.changed.outputs.any_changed == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./${{inputs.pkg}}/ci.ps1
        shell: pwsh

      - name: upload
        if: ${{github.event_name !='pull_request' || steps.changed.outputs.any_changed == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.pkg}}
          path: ./*/output/win-64/*.conda

      - name: publish
        if: ${{github.event_name !='pull_request' && success() }}
        run: |
          . ./scripts/setup.ps1

          if(Test-Path "./*/output/win-64/*.conda"){
            foreach ($pkg in Get-ChildItem "./*/output/win-64/*.conda") {
              $filename=Split-Path $pkg -Leaf
              $search_result=pixi search -c https://repo.prefix.dev/glatzel ${{inputs.pkg}}
              if (-not ("$search_result" -like "*$filename*")){
                write-output "::group::publish $pkg"
                pixi run rattler-build upload prefix -c glatzel "$pkg"
                write-output "::endgroup::"
              }
              else {write-output "No new package."}
            }
          }
          else {write-output "No new package."}
        shell: pwsh

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        if: ${{github.event_name !='pull_request' && success() }}
        with:
          token: ${{ github.token }}
          commit-message: "chore: update recipe"
          title: "chore: update recipe"
          branch: update-recipe
          base: main
          labels: action
          delete-branch: true
          add-paths: ./*/recipe.yaml
          assignees: Glatzel
          draft: true

