name: update
on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
env:
  WORKFLOW_NAME: ${{ github.workflow }}
jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Update
        run: ./scripts/update.ps1
        shell: pwsh
        env:
          GH_TOKEN: ${{github.token}}
