name: update
on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
env:
  WORKFLOW_NAME: ${{ github.workflow }}
jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Update
        run: ./scripts/update.ps1
        shell: pwsh
        env:
          GH_TOKEN: ${{github.token}}
