context:
  name: houdini-launcher
package:
  version: "22.0.368"
  name: ${{ name }}
build:
  number: 0
requirements:
  build:
    - aria2
    - vinaya-cli
    - jq
tests:
  - package_contents:
      files:
        - houdini-launcher/bin/houdini-launcher*

extra:
  update: get-version-url -url "https://www.hwinfo.com/news.xml/" -pattern 'HWiNFO v(\d+\.\d+) released'
  changelog: echo "https://www.sidefx.com/changelog/"
