context:
  name: houdini-launcher
package:
  version: "22.0"
  name: ${{ name }}
build:
  number: 1
requirements:
  build:
    - aria2
    - vinaya-cli
    - jq
tests:
  - package_contents:
      bin:
        - ${{"install_houdini_launcher" if linux}}
      files:
        - ${{"houdini-launcher/bin/houdini_launcher.exe" if win}}

extra:
  update: echo "22.0"
  changelog: echo "https://www.sidefx.com/changelog/"
