context:
  name: houdini-launcher
package:
  version: "22.0.431"
  name: ${{ name }}
build:
  number: 0
requirements:
  build:
    - aria2
    - vinaya-cli
    - jq
tests:
  - package_contents:
      files:
        - ${{"bin/install_houdini_launcher.sh" if linux}}
        - ${{"houdini-launcher/bin/houdini_launcher.exe" if win}}

extra:
  update: gh api repos/sideeffects/SideFXLabs/tags --jq '.[0].name'
  changelog: echo "https://www.sidefx.com/changelog/"
