context:
  name: fresh-editor
package:
  version: "0.1.64"
  name: ${{ name }}
build:
  number: 1
  script: pwsh -Command "& ${{'$env:RECIPE_DIR' if win else '$RECIPE_DIR'}}/build-${{ name }}.ps1"
tests:
  - script: pwsh -Command "& ${{'$env:PREFIX' if win else '$PREFIX'}}/bin/fresh${{'.exe' if win}} --help"
